### PR TITLE
Release 8.11.0

### PR DESCRIPTION
**Pull request by bmorelli25**
**Do not merge until release day**

### CODE REVIEW

**Comment by bmorelli25** [comment]
@elasticmachine, run elasticsearch-ci/docs

**Comment by bmorelli25** [comment]
Just one bad link 🚀 

```
14:32:34 INFO:build_docs:Bad cross-document links:
14:32:34 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/enterprise-search/8.7/index.html contains broken links to:
14:32:34 INFO:build_docs:   - en/enterprise-search/current/start.html#start-documents
```

**Comment by leemthompo** [comment]
@elasticmachine, run elasticsearch-ci/docs

**Comment by bmorelli25** [comment]
The checks are all green, but I am rerunning again to be super sure.

**Comment by bmorelli25** [comment]
@elasticmachine, run elasticsearch-ci/docs rebuild

**Review by kilfoyle — APPROVED** [review]
LGTM!

**Comment by chriscressman** [comment]
@bmorelli25 I see the build is failing because I removed some Enterprise Search docs. I'm working on this now.

**Comment by kilfoyle** [comment]
I'll re-run the CI checks since @chriscressman's [Cloud PR](https://github.com/elastic/cloud/pull/121161) and the associated backports are now merged.

**Comment by kilfoyle** [comment]
@elasticmachine, run elasticsearch-ci/docs rebuild

**Comment by kilfoyle** [comment]
@elasticmachine, run elasticsearch-ci/docs rebuild

**Comment by kilfoyle** [comment]
`All cross-document links OK` 🥳

**Pull request merged**
