### PR TITLE
Drafts prototype

### PR DESCRIPTION
**Pull request by lcawl**
This is also a test

### CODE REVIEW

**Comment by gtback** [comment]
Looks like the build failed, but I can't tell if it's because of the branching stuff or something specific in the branch. Let me know if I can help figure anything out.

**Comment by lcawl** [comment]
There was a typo, but the errors that are expected (and ignored when using the command line and the --lenient option) are like this:

````
INFO:build_docs:asciidoctor: WARNING: ../../../../elasticsearch/docs/reference/monitoring/overview.asciidoc: line 28: can't read image [elasticsearch/docs/reference/monitoring/images/architecture.png] at any of ["/doc/cloud/docs/elasticsearch/docs/reference/monitoring/images/architecture.png", "/doc/elasticsearch/docs/elasticsearch/docs/reference/monitoring/images/architecture.png"...

INFO:build_docs:asciidoctor: WARNING: ../../../../kibana/docs/management/managing-licenses.asciidoc: line 21: can't read image [kibana/docs/images/management-license.png] at any of ["/doc/cloud/docs/kibana/docs/images/management-license.png", "/doc/elasticsearch/docs/kibana/docs/images/management-license.png"...
````

These will likely require changes to the source file to fix them, but I've avoided touching any source files so far with my Asciidoctor prototypes, since I didn't want to ill-affect existing behaviour.  It's also interesting that the Asciidoctor builds can find those files, whereas the docbuild cannot.

**Comment by lcawl** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by lcawl** [comment]
@elasticmachine run elasticsearch-ci/docs

**Pull request closed without merging**
