### PR TITLE
Change current branch to 7.14 

### PR DESCRIPTION
**Pull request by jmikell821**
Addresses #2163. 

DO NOT MERGE UNTIL RELEASE DAY.

### CODE REVIEW

**Comment by jmikell821** [comment]
@elasticmachine run elasticsearch-ci/docs rebuild

**Comment by lcawl** [comment]
@elasticmachine update branch

**Comment by lcawl** [comment]
@elasticmachine merge upstream

**Comment by lcawl** [comment]
@elasticmachine run elasticsearch-ci/docs rebuild

**Comment by lcawl** [comment]
@elasticmachine run elasticsearch-ci/docs rebuild

**Comment by jmikell821** [comment]
@elasticmachine run elasticsearch-ci/docs rebuild

**Review by chriscressman — APPROVED** [review]

**Pull request merged**
