### PR TITLE
Add new version of the docs for ecctl

### PR DESCRIPTION
**Pull request by alpar-t**
Part of the ecctl 1.2 release, accompanying ECE 2.8.0
Relates to https://github.com/elastic/ecctl/issues/436

### CODE REVIEW

**Review by gtback — APPROVED** [review]
LGTM! 🎸

**Comment by gtback** [comment]
Looks like there's one build failure that needs to be resolved:

> :asciidoctor: WARNING: invalid reference: ecctl-release-notes-v1.2.0-whats-new

If that's just waiting for elastic/ecctl#436 to get merged, then once it is you can just leave a commment here with: 

`@elasticmachine run elasticsearch-ci/docs`

to re-run the tests. After merging, we'll want to do a full rebuild since we're modifying the "current" version. Let me know if I can help with this.

**Comment by alpar-t** [comment]
I was under the impression that the change-log was already merged. 
@obierlaire will take over as release manager from here. Note that with this step and the docs rebuild the docs go live,  and we just need to  sync with marketing to update the download pages with ECCTL as well when we release 2.8.1 and 7.11.1

**Comment by obierlaire** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by obierlaire** [comment]
@elasticmachine update branch

**Comment by gtback** [comment]
Looks like this was fixed in master in elastic/ecctl#442 but needs to be backported to the 1.2 branch. cc: @elastic/cloud-writers

**Comment by kellyemurphy** [comment]
@obierlaire in file https://github.com/elastic/ecctl/blob/1.2/docs/release_notes/v1.2.0.adoc of the 1.2 branch, line 7, you'll need to change it to `<<{p}-release-notes-v1.2.0-bug-fixes,Bug fixes>> | <<{p}-release-notes-v1.2.0-changelog,Changelog>>`.

(I don't have write access to this repo)

**Review by nrichers — APPROVED** [review]
Docs build change LGTM. 🚀

**Comment by obierlaire** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by gtback** [comment]
@obierlaire it looks like PR elastic/ecctl#444 was also made to the master branch rather than the 1.2 branch. That's why the builds are still failing.

**Comment by obierlaire** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by gtback** [comment]
🎉 Build is passing. Sorry this took so long @obierlaire.

**Pull request merged**
