### PR TITLE
Update to ms45

### PR DESCRIPTION
**Pull request by mnewswanger**
Update cloud ms44 -> ms45

### CODE REVIEW

**Review by nrichers — APPROVED** [review]
LGTM! :shipit:

**Review by gtback — APPROVED** [review]

**Comment by gtback** [comment]
Yuck, it looks like a lot of broken links. I'm not sure if those are things that changed in ms-45 that need to be updated, or if something else is wrong.

**Comment by kellyemurphy** [comment]
Trying again for link checks.

**Comment by lcawl** [comment]
@elasticmachine, run elasticsearch-ci/docs rebuild

**Comment by jrodewig** [comment]
@elasticmachine run elasticsearch-ci/docs rebuild

**Comment by lcawl** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by gtback** [comment]
Admin-merging this, since the broken ECCTL links should have gotten fixed in other PRs that got merged while the the most recent check was running.

**Pull request merged**
