### PR TITLE
Clean up """ed strings in copy-as-curl

### PR DESCRIPTION
**Pull request by nik9000**
Clean up """ed strings output by copy-as-curl so they look fairly good.

* Trim leading newlines
* Trim leading whitespace from the first line
* Trim the same amount of whitespace from each subsequent line
* Trim trailing whitespace

### CODE REVIEW

**Comment by archanid** [comment]
Can you give an example before and after output as a result of these changes? I'm curious why we do `Trim the same amount of whitespace from each subsequent line`

**Comment by talevy** [comment]
@archanid I was wondering the same thing, so I tried it here:

https://jsfiddle.net/vgsbms7a/16/

**Comment by nik9000** [comment]
Sure!

This is what we are transforming:
```
GET hockey/_search
{
  "query": {
    "function_score": {
      "script_score": {
        "script": {
          "lang": "painless",
          "source": """
            int total = 0;
            for (int i = 0; i < doc['goals'].length; ++i) {
              total += doc['goals'][i];
            }
            return total;
          """
        }
      }
    }
  }
}
```

The change in this PR is around the `"""`ed field.

Here is the output with this PR:
```
curl -XGET 'localhost:9200/hockey/_search?pretty' -H 'Content-Type: application/json' -d'
{
  "query": {
    "function_score": {
      "script_score": {
        "script": {
          "lang": "painless",
          "source": "int total = 0;\nfor (int i = 0; i < doc[\u0027goals\u0027].length; ++i) {\n  total += doc[\u0027goals\u0027][i];\n}\nreturn total;"
        }
      }
    }
  }
}
'
```

And here is what it looks like without this PR:

```
curl -XGET 'localhost:9200/hockey/_search?pretty' -H 'Content-Type: application/json' -d'
{
  "query": {
    "function_score": {
      "script_score": {
        "script": {
          "lang": "painless",
          "source": "\n            int total = 0;\n            for (int i = 0; i < doc[\u0027goals\u0027].length; ++i) {\n              total += doc[\u0027goals\u0027][i];\n            }\n            return total;\n          "
        }
      }
    }
  }
}
'
```

**Comment by talevy** [comment]
should we be trimming trailing whitespace from each line?

**Comment by nik9000** [comment]
> should we be trimming trailing whitespace from each line?

Trailing whitespace isn't a normal thing in the examples though. So I don't think it is worth it.

**Comment by talevy** [comment]
good enough for me

**Comment by nik9000** [comment]
Thanks for reviewing @archanid and @talevy! I'm going to get this merged so we can have nicer copy-as-curls for now. If you find anything else I'd be happy to change it!

**Pull request merged**
