### PR TITLE
Update branch version to MS-58

### PR DESCRIPTION
**Pull request by alaudazzi**
This PR changes current to MS 58 for ESS.

### CODE REVIEW

**Review by kilfoyle — APPROVED** [review]

**Review by gtback — APPROVED** [review]
LGTM!

**Comment by gtback** [comment]
@elasticmachine run elasticsearch-ci/docs rebuild

**Comment by gtback** [comment]
@alaudazzi Looks like this passed after re-running with the backport PR merged to fix the broken links 🙌🏻 .

**Comment by alaudazzi** [comment]
@gtback Thank you!

**Pull request merged**
