### PR TITLE
Update ES clients to use `stackcurrent` and `stacklivemain` variables

### PR DESCRIPTION
**Pull request by jrodewig**
Updates the following ES clients docs to use the `stackcurrent` and `stacklivemain` variables:

- Java
- JavaScript
- Ruby
- Go
- .NET
- PHP
- Python

This will bump the `current` branch for these docs to 8.0. It'll also ensure the clients stay synced with stack releases in the future.

This **does not** update the current version for the Perl or Rust clients.

### CODE REVIEW

**Review by philkra — APPROVED** [review]
LGTM -- I double checked the repos and the branches are in place. Thanks James for opening the PR

**Comment by jrodewig** [comment]
This change is causing some links from the [legacy elasticsearch.js docs](https://www.elastic.co/guide/en/elasticsearch/client/elasticsearch-js/current/index.html) to the [ES JS client docs](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/8.0/index.html) to break. To fix those links, I've opened https://github.com/elastic/elasticsearch-js/pull/1634 to add some related redirects. I've also reached out to the clients team about updating the legacy docs.

We should also investigate whether we can use the `stackcurrent` and `stacklivemain` variables for these client docs instead of hardcoding the `current` and `live` branches. I'll reach out to the clients team about this on Monday.

**Comment by jrodewig** [comment]
I spoke with @philkra and confirmed that we can use the `stackcurrent` and `stacklivemain` variables.

I'll merge this in once https://github.com/elastic/elasticsearch-js/pull/1634 is merged and backported.

**Comment by philkra** [comment]
Thanks @jrodewig , the PR https://github.com/elastic/elasticsearch-js/pull/1634 is merged on `main`

**Review by gtback — APPROVED** [review]
LGTM once the builds pass.

**Pull request merged**
