### PR TITLE
Make ECS 1.10 the current release

### PR DESCRIPTION
**Pull request by kgeller**
Do not merge. Please let the ECS team merge this at the appropriate time.

### CODE REVIEW

**Review by gtback — APPROVED** [review]
LGTM! Feel free to merge when ready.

After merging this, please run a full rebuild of the docs to pick up the change to "current". Let me know if I can help.

**Comment by ebeahan** [comment]
Thanks, @gtback!

I don't believe the ECS conf change here is the cause of the current CI failure:

```
INFO:build_docs:ERROR building Elasticsearch Guide version master
INFO:build_docs:asciidoctor: ERROR: dependencies-versions.asciidoc: line 6: include file not found: /tmp/docsbuild/N139sHXi1u/elasticsearch/build-tools-internal/version.properties
```

Looks like an unrelated Elasticsearch change may be causing the CI job to fail here?

**Comment by gtback** [comment]
Yep, that's an unrelated issue that was fixed recently.

**Comment by gtback** [comment]
@elasticmachine run elasticsearch-ci/docs

**Pull request merged**
