### PR TITLE
Update code examples style

### PR DESCRIPTION
**Pull request by nik9000**
We'd like to customize the style of the code examples. To do that we need
to serve the style locally. To do that we need to serve `code-prettify`
locally. This does that by copying it into `resources/web/prettify` and
modifying it to work properly with parcel and bundling it alone with the
rest of our js.

As a bonus this adds support for SQL which we've started to include in
the ES docs.

### CODE REVIEW

**Comment by nik9000** [comment]
I'm keeping this as a WIP until we can figure out how get the licenses into docs.js.

**Comment by haywoood** [comment]
Good news and bad news.

Good news: You can pass options to terser.js by creating a `.terserrc` file in the `docs_js` directory with this config to keep license comments around

```javascript
{
  "output": {
    "comments": "/license/"
  }
}
```

The bad news is, this doesn't work with the experimental tree shaking flag enabled (hours later). I kept seeing the correct output during the compilation step, but with that option it goes through an _additional_ step which removes comments. 

Removing this flag inflates the size of the bundle to 250kb sadly, so that's not an option. Perhaps we need to manually prepend licenses to the compiled file for now while we look to see if the bug is easy to solve upstream. Or we could just find another solution, maybe the branch that uses the Clojurescript compiler can do this out of the box.

**Comment by nik9000** [comment]
> hours later

Damn! Thanks for filing https://github.com/parcel-bundler/parcel/issues/3322



> Perhaps we need to manually prepend licenses to the compiled file for now while we look to see if the bug is easy to solve upstream.

Done. The file is now 77k. That is 13k of license comments, the vast majority are MIT with a couple of Apache 2.

**Comment by nik9000** [comment]
I'm removing `WIP` because I've got the license in there. I think this is ready so long as folks are happy with it. I've pinged @Adrian-J and @debadair for their approval. Here are some previews:
* [lots going on here](http://docs_1044.docs-preview.app.elstc.co/guide/en/elasticsearch/reference/master/search-aggregations-metrics-geobounds-aggregation.html)
* [check out the horizontal scrolling](http://docs_1044.docs-preview.app.elstc.co/guide/en/elasticsearch/reference/master/search-aggregations-metrics-cardinality-aggregation.html#_script_3)
* [syntax highlighting for SQL work now](http://docs_1044.docs-preview.app.elstc.co/guide/en/elasticsearch/reference/master/sql-functions-grouping.html). It isn't perfect at all but it is better than nothing and I got it nearly "for free".

**Comment by nik9000** [comment]
@elasticmachine, elasticsearch-ci/docs

**Comment by nik9000** [comment]
@elasticmachine, elasticsearch-ci/docs

**Comment by nik9000** [comment]
@elasticmachine, elasticsearch-ci/docs

**Comment by nik9000** [comment]
@elasticmachine, elasticsearch-ci/docs

**Comment by nik9000** [comment]
@elasticmachine, elasticsearch-ci/docs

**Comment by nik9000** [comment]
@elasticmachine, elasticsearch-ci/docs

**Comment by nik9000** [comment]
@elasticmachine, elasticsearch-ci/docs

**Comment by nik9000** [comment]
@elasticmachine, run elasticsearch-ci/docs

**Comment by nik9000** [comment]
@elasticmachine, run elasticsearch-ci/docs

**Comment by nik9000** [comment]
@elasticmachine, run elasticsearch-ci/docs with rebuild

**Comment by nik9000** [comment]
@elasticmachine, run elasticsearch-ci/docs with rebuild

**Comment by debadair** [comment]
I added some feedback on the design in the issue: https://github.com/elastic/clients-team/issues/49#issuecomment-519263095. At a minimum, I think the callout styling needs to be updated to suit the dark theme.

**Comment by nik9000** [comment]
I'll try and address it in this PR, but if it goes crazy I'll separate it
out.

**Pull request merged**
