### PR TITLE
Switch the ECS docs to Asciidoctor

### PR DESCRIPTION
**Pull request by nik9000**
Switches the core of the docs build for the ECS docs from the
unmaintained AsciiDoc project to the actively developed Asciidoctor
project.

### CODE REVIEW

**Comment by nik9000** [comment]
Needs https://github.com/elastic/ecs/pull/430 to be merged and backported to the 1.0 branch before I can make a diff.

**Comment by nik9000** [comment]
@webmat, this is what merging the PR would do the generated docs. If you are ok
with these changes then we can merge this and your docs will be regenerated
using Asciidoctor when the docs next build.

ecs-faq.html:
```patch
- AsciiDoc
+ Asciidoctor
@@ -739,10 +739,10 @@
            is identical to ingesting the following JSON:
           </p>
           <div class="pre_wrapper">
-           <pre class="programlisting prettyprint lang-json">"user": {
-  "firstname": "Nicolas",
-  "lastname": "Ruflin"
-}</pre>
+           <pre class="programlisting prettyprint lang-json">    "user": {
+      "firstname": "Nicolas",
+      "lastname": "Ruflin"
+    }</pre>
           </div>
           <p>
            In Elasticsearch,
```
AsciiDoc seems to be eating the leading indentation. If don't mean to have it
the you are better off wrapping the snippet in `----`s.

ecs-reference.html:
```patch
- AsciiDoc
+ Asciidoctor
@@ -621,7 +621,7 @@
            </ul>
           </div>
           <h3>
-           <a id="_my_events_don_8217_t_map_with_ecs">
+           <a id="_my_events_dont_map_with_ecs">
            </a>
            My events don’t map with ECS
            <a class="edit_me" href="https://github.com/elastic/ecs/edit/1.0/docs/index.asciidoc" rel="nofollow" title="Edit this page on GitHub">
```
These happen because you aren't explicit about your section titles. AsciiDoc's
rules for building these from the text are kind of weird. Asciidoctor's are
*better*, but sometimes the produce different output. Like this time. Sometimes
this means we get different page URLs too! Since it is just an anchor I'm
generally ok with changing these. Though you might want to be explicit here.

**Comment by nik9000** [comment]
Thanks for reviewing @karenzone!

**Comment by webmat** [comment]
Awesome!

I guess I'll go update the make targets in the ECS repo now 🏃 😂

**Pull request merged**
