### PR TITLE
Get Ingest Management docs building

### PR DESCRIPTION
**Pull request by dedemorton**
Initial PR to add ingest management docs.

Draft until we get the initial files in place.

Open issues:
- [x] Finalize location of the content. The options are:
  - Put under Elastic Stack
  - Put under Observability: APM, Logs, Metrics, and Uptime
  - Rename "Beats: Collect, Parse, and Ship" to "Collect, Parse, and Ship" and put under there.

UPDATE: Decision was to put under Beats for now because this feature is experimental.

### CODE REVIEW

**Comment by gtback** [comment]
CI is failing because `stackcurrent` (i.e. 7.7) is not in the list of branches getting built.

**Comment by dedemorton** [comment]
> CI is failing because stackcurrent (i.e. 7.7) is not in the list of branches getting built.

Fixed! The build might fail again because we don't have all the asciidoc source files properly merged yet.

**Comment by dedemorton** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by dedemorton** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by dedemorton** [comment]
@elasticmachine run elasticsearch-ci/docs

**Pull request merged**
