### PR TITLE
Updated expired yarn.gpg key

### PR DESCRIPTION
**Pull request by redNixon**
Updated the yarn.gpg key referenced in #2052

File committed is https://dl.yarnpkg.com/debian/pubkey.gpg which as of right now has these details: 
```
curl -s https://dl.yarnpkg.com/debian/pubkey.gpg | gpg  --keyid-format=long -
gpg: WARNING: no command supplied.  Trying to guess what you mean ...
pub   rsa4096/1646B01B86E50310 2016-10-05 [SC]
      72ECF46A56B4AD39C907BBB71646B01B86E50310
uid                           Yarn Packaging <yarn@dan.cx>
sub   rsa4096/02820C39D50AF136 2016-10-05 [E]
sub   rsa4096/D101F7899D41F3C3 2016-10-05 [S] [expired: 2017-10-05]
sub   rsa4096/46C2130DFD2497F5 2016-10-30 [S] [expired: 2019-01-01]
sub   rsa4096/E074D16EB6FF4DE3 2017-09-10 [S] [expired: 2019-01-01]
sub   rsa4096/23E7166788B63E1E 2019-01-02 [S] [expires: 2023-01-24]
sub   rsa4096/4F77679369475BAA 2019-01-11 [S] [expires: 2023-01-24]
```

### CODE REVIEW

**Comment by kovyrin** [comment]
Tested it on my machine while working on Enterprise Search docs and it works as expected. Thank you for fixing the issue! 🙇

**Comment by redNixon** [comment]
fwiiw I did sign the the CLA after the bot threw the warning

**Review by kovyrin — APPROVED** [review]

**Comment by gtback** [comment]
jenkins test this please

**Review by gtback — APPROVED** [review]
Looks great! Thanks @redNixon 

I'll merge this as soon as the tests pass.

**Pull request merged**
