### PR TITLE
Update CODEOWNERS

### PR DESCRIPTION
**Pull request by glitteringkatie**
Reduce noise for docs-engineering, add us when you need us!

### CODE REVIEW

**Review by bmorelli25 — APPROVED** [review]
I'm fine with this. Maybe the best solution is to create a new team (a know, another new team) that has all of the codeowners for this repo listed out. We could then use the GitHub team assignment rules to only ping x number of people per PR. That would reduce noise for all.

I'm open to other ideas as well.

**Comment by leemthompo** [comment]
@bmorelli25 I'm not sure why I'm a code owner here either TBH 😄

**Comment by bmorelli25** [comment]
@leemthompo codeowners were added in https://github.com/elastic/docs/pull/2827. Here are the details without pinging everyone:

> * @\elastic/docs-release-team: This team includes, @\bmorelli25, @\KOTungseth, @\abdonpijpelink, @\joepeeples, and @\lcawl
> * The writer who knows the most about how the classic doc system works: @\colleenmcginnis
> * The two highest contributors (based on number of commits in the past year) to this repo outside of the above folks: @\kilfoyle and @\leemthompo

I'd like to keep you as a codeowner due to your commit history in this repo and your timezone. The new round-robin review format introduced in [`c2928a3`](https://github.com/elastic/docs/pull/2868/commits/c2928a3eea83736c27061b00b041594591adfb81) should greatly reduce the noise you experience. Also, the docs migration is nearly complete, which has caused a lot more PRs than this repo typically sees.

**Comment by glitteringkatie** [comment]
Congrats @leemthompo for being our docs MVP! Your reward is 100000 code reviews 🎉

**Review by bmorelli25 — APPROVED** [review]

**Comment by leemthompo** [comment]
@bmorelli25 thanks for the context, I missed that broadcast somehow 😃

**Pull request merged**
