### PR TITLE
Move cloud native ingest docs to ingest section of docs landing page

### PR DESCRIPTION
**Pull request by dedemorton**
Moves "cloud native" methods of data ingestion to the ingest section under "Browse all docs".

One could argue that the [Amazon Kinesis Data Firehose Ingest Guide](https://www.elastic.co/guide/en/kinesis/current/index.html) does belong under cloud, but IMO it does not belong under the description "Provision, manage, and monitor the Elastic Stack".

The [Elastic Serverless Forwarder Guide](https://www.elastic.co/guide/en/esf/current/index.html) on the other hand is not cloud-specific and shouldn't be under that category.

I think it would be good to keep all the data ingestion topics under ingest. Thoughts?

The section seems to be mostly organized alphabetically, with Beats books being grouped together, so I added these guides in alphabetical order. I'm open to other suggestions.

### CODE REVIEW

**Comment by bmorelli25** [comment]
run docs-build

**Comment by dedemorton** [comment]
run docs-build

**Review by bmorelli25 — APPROVED** [review]
[preview](https://docs_bk_2910.docs-preview.app.elstc.co/guide/index.html) lgtm

**Comment by dedemorton** [comment]
I'm going to merge this. If anyone objects, come talk to me.

**Pull request merged**
