### PR TITLE
docs: move ingest docs

### PR DESCRIPTION
**Pull request by bmorelli25**
Moves the source of the ingest documentation.

Related: https://github.com/elastic/ingest-docs/pull/78

For: https://github.com/elastic/observability-docs/issues/2411

### CODE REVIEW

**Review by dedemorton — APPROVED** [review]
LGTM (contingent on build passing, of course)

**Comment by bmorelli25** [comment]
Close! 

```
19:15:40 INFO:build_docs:Bad cross-document links:
19:15:40 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/guide/8.3/apm-quick-start.html contains broken links to:
19:15:40 INFO:build_docs:   - en/fleet/8.3/filter-agent-list-by-tags.html
19:15:40 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/observability/8.3/ingest-traces.html contains broken links to:
19:15:40 INFO:build_docs:   - en/fleet/8.3/filter-agent-list-by-tags.html
```

**Comment by bmorelli25** [comment]
I _think_ I fixed it. See https://github.com/elastic/ingest-docs/tree/8.3/docs/en/ingest-management. Trying again...

**Comment by bmorelli25** [comment]
@elasticmachine, run elasticsearch-ci/docs

**Pull request merged**
