### PR TITLE
Add 8.13 branch

### PR DESCRIPTION
**Pull request by joepeeples**
Contributes to https://github.com/elastic/dev/issues/2505 by adding a branch for 8.13 to `conf.yaml`.

> [!IMPORTANT]
> Merge this PR after all teams have created a new 8.13 branch in their repos.
> ✅ ~~Also need to wait until https://github.com/elastic/docs/pull/2937 is merged to use 8.13 attributes.~~

### CODE REVIEW

**Review by kilfoyle — APPROVED** [review]
LGTM! 🦕

**Comment by joepeeples** [comment]
run docs-build

**Comment by joepeeples** [comment]
run docs-build

**Comment by joepeeples** [comment]
run docs-build

**Comment by leemthompo** [comment]
run docs-build

**Comment by joepeeples** [comment]
run docs-build

**Comment by joepeeples** [comment]
run docs-build

**Comment by joepeeples** [comment]
run docs-build

**Comment by joepeeples** [comment]
run docs-build

**Comment by joepeeples** [comment]
run docs-build

**Pull request merged**
