### PR TITLE
Promote ECK 2.3

### PR DESCRIPTION
**Pull request by barkbay**
This promotes ECK `2.3` release branch to current.

It should be merged:
* after #2454
* once ECK 2.3 is released

### CODE REVIEW

**Review by gtback — APPROVED** [review]

**Comment by barkbay** [comment]
Build failed with:

```
06:46:39 INFO:build_docs:Bad cross-document links:
06:46:39 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/elasticsearch/reference/master/foreach-processor.html contains broken links to:
06:46:39 INFO:build_docs:   - en/elasticsearch/plugins/master/ingest-attachment-with-arrays.html
06:46:39 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/workplace-search/master/content-sources-content-extraction.html contains broken links to:
06:46:39 INFO:build_docs:   - en/elasticsearch/plugins/master/ingest-attachment-fields.html
```

**Comment by barkbay** [comment]
Still failing, but only with

```
11:21:32 INFO:build_docs:Bad cross-document links:
11:21:32 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/workplace-search/master/content-sources-content-extraction.html contains broken links to:
11:21:32 INFO:build_docs:   - en/elasticsearch/plugins/master/ingest-attachment-fields.html
```

**Comment by alaudazzi** [comment]
@gtback @debadair 
Can you help here? It seems that the issue is related to ES repo?

**Comment by barkbay** [comment]
@elasticmachine run elasticsearch-ci/docs rebuild

**Comment by barkbay** [comment]
This seems to have been solved by the last build attempt.

Thanks @alaudazzi for your help 🙇

**Pull request merged**
