### PR TITLE
change .NET APM docs to “x” versioning

### PR DESCRIPTION
**Pull request by bmorelli25**

### CODE REVIEW

**Comment by bmorelli25** [comment]
@elasticmachine, run elasticsearch-ci/docs

**Comment by bmorelli25** [comment]
I think (and hope) that these will be fixed when @gregkalapos pushes to [`1.x`](https://github.com/elastic/apm-agent-dotnet/tree/1.x).

**Comment by gregkalapos** [comment]
@elasticmachine, run elasticsearch-ci/docs

_([`1.x`](https://github.com/elastic/apm-agent-dotnet/tree/1.x) updated)._

**Review by gregkalapos — APPROVED** [review]
Thanks @bmorelli25!

**Pull request merged**
