### PR TITLE
Jenkins/Buildkite branch comparison build step

### PR DESCRIPTION
**Pull request by nkammah**

### CODE REVIEW

**Review by bmorelli25 — APPROVED** [review]
Looks neat! Thanks for putting this together. Is there any way to test it?

**Review by gtback — APPROVED** [review]
I haven't tried to run this, but it seems like it would be really useful 😁

**Comment by bmorelli25** [comment]
Should the [Buildkite vs Jenkins diff](https://github.com/elastic/built-docs/compare/docs_bk_2863..docs_2863) be this big?

```
Showing 22,628 changed files with 4,737,324 additions and 6,996 deletions.
```

**Comment by nkammah** [comment]
> Should the [Buildkite vs Jenkins diff](https://github.com/elastic/built-docs/compare/docs_bk_2863..docs_2863) be this big?
> 
> ```
> Showing 22,628 changed files with 4,737,324 additions and 6,996 deletions.
> ```

that's because I used this PR to test it against a bunch of other repos/PT :D

**Comment by nkammah** [comment]
I will merge this is for now- there are other optimizations we could do, but I have already spent too much time on this for a script that will go away once the validation is over, and want to start reaping off the benefits of it while (potentially) incrementally making this better, eg:

* (optimization) check if the Jenkins branch exists and then sleep if it does not
* (better reporting) report violations in slack

**Comment by thbkrkr** [comment]
> there are other optimizations we could do, but I have already spent too much time on this for a script that will go away once the validation is over,

Out of curiosity, how long will validation take? This script seems to increase the duration by almost +50% (from ~15min to ~24min). We have a PR build that takes ~15 minutes, so now we're waiting for the doc PR build, rather than ours.

**Pull request merged**
