### PR TITLE
Testing search

### PR DESCRIPTION
**Pull request by brianjolly**
For testing only. Please do not merge.

### CODE REVIEW

**Comment by gtback** [comment]
@brianjolly do you still need this branch/PR?

**Comment by brianjolly** [comment]
Hi @gtback , if we could keep it for a little longer would be helpful. We're using it to test switching the search in our navbar to use [Search-UI](https://www.elastic.co/enterprise-search/search-ui).

**Comment by gtback** [comment]
Ah, if you're still using it, no worries. 🎉

**Comment by laurent-qa** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by laurent-qa** [comment]
Hi @gtback 

Has something changed?
I tried the same command than @brianjolly  did above but it doesn't look like it worked.

Thank you

**Comment by gtback** [comment]
Hi @laurent-qa 👋🏻  . It looks like the job [ran again successfully](https://elasticsearch-ci.elastic.co/job/elastic+docs+pull-request+build/659/) right after your comment. It can take up to 30 minutes for the job to finish, during which the check will probably show as "pending" in Yellow.

**Pull request closed without merging**
