### PR TITLE
ece: Update branches for upcoming 2.12.0 release

### PR DESCRIPTION
**Pull request by marclop**
## Description
**DO NOT MERGE BEFORE SEPTEMBER 21**

Updates the branches for: ECE, ecctl and the Terraform Provider for the
upcoming ECE 2.12.0 release.

**DO NOT MERGE BEFORE SEPTEMBER 21**

### CODE REVIEW

**Review by gtback — APPROVED** [review]
LGTM!

**Comment by obierlaire** [comment]
blocked by https://github.com/elastic/cloud/pull/89003

**Comment by obierlaire** [comment]
@elasticmachine update branch

**Comment by obierlaire** [comment]
@elasticmachine run elasticsearch-ci/docs

**Pull request merged**
