### PR TITLE
Switch APM Server to Asciidoctor

### PR DESCRIPTION
**Pull request by bmorelli25**
## See https://github.com/elastic/apm-server/issues/1965 for all updates.
📖⛷👨‍⚕

### CODE REVIEW

**Comment by bmorelli25** [comment]
Sorry, tagged the wrong Nik initially.

**Comment by bmorelli25** [comment]
Well, dang.
```log
INFO:build_docs:/tmp/docsbuild/target_repo/html/en/apm/server/7.1/index.xml:1533: element xref: validity error : IDREF attribute linkend references an unknown ID "configuration-autodiscover-hints"
```
Which is here:
https://github.com/elastic/apm-server/blame/4e817c7da50b58e8a8ba9dbafed4902b3ad3a0b5/docs/copied-from-beats/shared-docker.asciidoc#L198-L217

The problem is that this shouldn't even be executed. The if should evaluate to false and not display at all.

**Comment by nik9000** [comment]
I talked with Brandon about this and we tracked it down to complex ifevals.
Asciidoctor silently considers then all true. I believe this is a bug that
they fixed in a version after the one we are using!

**Comment by bmorelli25** [comment]
@elasticmachine, run elasticsearch-ci/docs

**Comment by bmorelli25** [comment]
```
09:33:28 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/agent/js-base/4.x/getting-started.html:
09:33:28 INFO:build_docs:   - en/apm/server/current/configuration-rum.html#_literal_allow_origins_literal
09:33:28 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/agent/js-base/current/getting-started.html:
09:33:28 INFO:build_docs:   - en/apm/server/current/configuration-rum.html#_literal_allow_origins_literal
09:33:28 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/agent/js-base/master/getting-started.html:
09:33:28 INFO:build_docs:   - en/apm/server/current/configuration-rum.html#_literal_allow_origins_literal
09:33:28 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/agent/rum-js/4.x/getting-started.html:
09:33:28 INFO:build_docs:   - en/apm/server/current/configuration-rum.html#_literal_allow_origins_literal
09:33:28 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/agent/rum-js/current/getting-started.html:
09:33:28 INFO:build_docs:   - en/apm/server/current/configuration-rum.html#_literal_allow_origins_literal
09:33:28 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/agent/rum-js/master/getting-started.html:
09:33:28 INFO:build_docs:   - en/apm/server/current/configuration-rum.html#_literal_allow_origins_literal
09:33:28 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/cloud-heroku/current/ech-manage-apm-settings.html:
09:33:28 INFO:build_docs:   - en/apm/server/7.3/configuration-rum.html#_literal_library_pattern_literal
09:33:28 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/cloud-heroku/release-ms-25/ech-manage-apm-settings.html:
09:33:28 INFO:build_docs:   - en/apm/server/7.3/configuration-rum.html#_literal_library_pattern_literal
09:33:28 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/cloud/current/ec-manage-apm-settings.html:
09:33:28 INFO:build_docs:   - en/apm/server/7.3/configuration-rum.html#_literal_library_pattern_literal
09:33:28 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/cloud/release-ms-25/ec-manage-apm-settings.html:
09:33:28 INFO:build_docs:   - en/apm/server/7.3/configuration-rum.html#_literal_library_pattern_literal
```

**Comment by bmorelli25** [comment]
@elasticmachine, run elasticsearch-ci/docs

**Comment by bmorelli25** [comment]
Oooo exciting! `elasticsearch-ci/docs` passes! Still a lot to do though. 

Blocked by:
- [ ] https://github.com/elastic/cloud/pull/38301
- [ ] the backport for ^
- [ ] https://github.com/elastic/apm-agent-rum-js/pull/387
- [ ] https://github.com/elastic/apm-agent-rum-js/pull/388
- [ ] removing python from <= 6.8

**Comment by bmorelli25** [comment]
@elasticmachine, run elasticsearch-ci/docs

**Comment by bmorelli25** [comment]
To consolidate things, I'm going to stop posting updates in this PR. **All updates will now be in the meta issue: elastic/apm-server#1965.**

**Comment by bmorelli25** [comment]
Everything looks ready 🤞. I'm waiting until the 7.4 branching is complete before merging.

**Pull request merged**
