### PR TITLE
Update current of ECE to 2.8

### PR DESCRIPTION
**Pull request by alpar-t**
Preparing the release of ECE 2.8

### CODE REVIEW

**Comment by gtback** [comment]
I think you'll also want to update the `mapCloudEceToCloudAssets` mapping around line 747 to include the new branch. Is that right, @nrichers ?

**Comment by gtback** [comment]
Sorry @alpar-t , I was looking at the build failure and I missed something. It seems like you'll also need to update `mapCloudEceToClientsTeam` as well. See #1992 for the last ECE update.

**Review by nrichers — CHANGES_REQUESTED** [review]
As @gtback pointed out, you also need to update mapCloudEceToClientsTeam around line 763. Thank you!

**Review by gtback — APPROVED** [review]
This looks good now, and the builds are passing. Want to give this another look @nrichers ?

**Review by nrichers — APPROVED** [review]
LGTM! 🚀 Note that after you merge this PR on release day, you will need to run a 'rebuild' doc build to update current and the version drop-down. The instructions and link to the Elastic doc builds are in your 2.8.0 issue. (Don't merge until you have released the code, as the changes will go out in 30 - 60 minutes.)

**Comment by alpar-t** [comment]
Build triggered in https://elasticsearch-ci.elastic.co/job/elastic+docs+master+build/250/console

**Pull request merged**
