### PR TITLE
Add config for ECE 3.0.0 and Ecctl 1.8.0

### PR DESCRIPTION
**Pull request by alpar-t**
Part of release operations.

### CODE REVIEW

**Comment by gtback** [comment]
@alpar-t it seems like our formatter is not happy with these changes (which I assume you're trying to automate in some way? 😉 ). I don't know if it's the tabs or the JSON-style list in YAML; this is valid YAML syntax but I'm not sure our parser likes it. 

Would it be possible to do something like this instead?

```yaml
        branches:
        - {'ms-69': 3.0}
        - {'ms-65': '2.13'}
        - {'ms-62': '2.12'}
        - {'ms-59': '2.11'}
        - {'ms-57': '2.10'}
        - {'ms-53': '2.9'}
        - {'ms-49': '2.8'}
        - {'ms-47': '2.7'}
        - {'release-ms-41': '2.6'}
        - '2.5'
        - '2.4'
        - '2.3'
        - '2.2'
        - '2.1'
        - '2.0'
        - '1.1'
        - '1.0'
```

**Comment by gtback** [comment]
On to a new error:

```
include file not found: /tmp/docsbuild/8V3uw1RaFL/cloud/docs/ece-version.asciidoc
```

This is the file that is automatically generated by the Cloud Gradle builds but not by our docs builds.

**Comment by v1v** [comment]
run elasticsearch-ci/docs

**Comment by alpar-t** [comment]
run elasticsearch-ci/docs

**Comment by alpar-t** [comment]
I'm not sure the current failure relates to this PR

**Comment by gtback** [comment]
> I'm not sure the current failure relates to this PR

We got past the earlier error but now have some broken links. 

```
03:23:29 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/cloud-enterprise/2.10/ece-release-notes-2.9.0.html contains broken links to:
03:23:29 INFO:build_docs:   - en/cloud-enterprise/current/Deployments_-_IP_Filtering_-_CRUD.html
03:23:29 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/cloud-enterprise/2.11/ece-release-notes-2.9.0.html contains broken links to:
03:23:29 INFO:build_docs:   - en/cloud-enterprise/current/Deployments_-_IP_Filtering_-_CRUD.html
03:23:29 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/cloud-enterprise/2.12/ece-release-notes-2.9.0.html contains broken links to:
03:23:29 INFO:build_docs:   - en/cloud-enterprise/current/Deployments_-_IP_Filtering_-_CRUD.html
03:23:29 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/cloud-enterprise/2.13/ece-release-notes-2.9.0.html contains broken links to:
03:23:29 INFO:build_docs:   - en/cloud-enterprise/current/Deployments_-_IP_Filtering_-_CRUD.html
03:23:29 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/cloud-enterprise/2.9/ece-release-notes-2.9.0.html contains broken links to:
03:23:29 INFO:build_docs:   - en/cloud-enterprise/current/Deployments_-_IP_Filtering_-_CRUD.html
03:23:29 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/cloud-enterprise/3.0/ece-release-notes-2.9.0.html contains broken links to:
03:23:29 INFO:build_docs:   - en/cloud-enterprise/current/Deployments_-_IP_Filtering_-_CRUD.html
03:23:29 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/cloud-enterprise/current/ece-release-notes-2.9.0.html contains broken links to:
03:23:29 INFO:build_docs:   - en/cloud-enterprise/current/Deployments_-_IP_Filtering_-_CRUD.html
```
These are links from the 2.9 release notes (in all branches of the ECE docs) that go to a page `Deployments_-_IP_Filtering_-_CRUD.html` which is presumably in the 2.13 docs but not the 3.0 docs. 

Paging @kilfoyle (sorry if there's another writer who typically handles this stuff, but I saw you made the release notes PR for 3.0.0).

**Comment by kilfoyle** [comment]
@gtback thanks for the heads-up! I'll get these links fixed today.

**Comment by kilfoyle** [comment]
@elasticmachine, run elasticsearch-ci/docs

**Review by gtback — APPROVED** [review]

**Pull request merged**
