### PR TITLE
Style: Move the * rule into guide

### PR DESCRIPTION
**Pull request by nik9000**
This should prevent us from modifying the header and footer.

### CODE REVIEW

**Comment by nik9000** [comment]
I'm think it might be nice to remove the `*` from that rule to be honest. That way we inherit properly. But I think that is a bigger change.

**Comment by nik9000** [comment]
So I figured I could make this fairly small change for now.

**Comment by brianjolly** [comment]
Hi @nik9000 , this looks good to me :)

**Comment by nik9000** [comment]
Thanks for reviewing @brianjolly !

**Pull request merged**
