### PR TITLE
Switch the painless book to direct_html

### PR DESCRIPTION
**Pull request by nik9000**
Direct html is faster and more customizable. It is the future!

### CODE REVIEW

**Comment by nik9000** [comment]
I'm opening this to generate a diff and will update it once I have a look at the diff.

**Comment by nik9000** [comment]
My diff found one thing which we should get fixed real soon now: #1563

**Comment by nik9000** [comment]
Now that the fix is in I'm going to rebuild the diff and recheck.

**Comment by nik9000** [comment]
The diff is now empty so I'm merging! @jdconrad, please update the command you use to build the book locally.

**Comment by jdconrad** [comment]
Thanks @nik9000! Will change my docs flow accordingly.

**Pull request merged**
