### PR TITLE
Drop jquery cookie

### PR DESCRIPTION
**Pull request by nik9000**
*now* we're not using it.

### CODE REVIEW

**Comment by nik9000** [comment]
@brianjolly, I think you removed the last thing that needs this.

**Comment by brianjolly** [comment]
Yes, I'm pretty sure the last thing using it was the script.js we removed in https://github.com/elastic/docs/pull/1142. Lets just want until the preview builds to double check.

**Comment by nik9000** [comment]
@elasticmachine, run elasticsearch-ci/docs rebuild

**Comment by nik9000** [comment]
The preview for this one looks good!

**Pull request merged**
