### PR TITLE
Bump current to 8.16

### PR DESCRIPTION
**Pull request by lcawl**
Do not merge until release day

The following PRs/issues address broken links:

- https://github.com/elastic/kibana/pull/198854
- https://github.com/elastic/cloud/pull/133754
- https://github.com/elastic/search-docs-team/issues/220
- https://github.com/elastic/observability-docs/issues/4479

### CODE REVIEW

**Review by kilfoyle — APPROVED** [review]
LGTM! 🏇

**Comment by leemthompo** [comment]
There's just a couple backports left to merge for https://github.com/elastic/search-docs-team/issues/220 to be all sewn up 🤞

**Comment by bmorelli25** [comment]
APM links should be fixed!

**Comment by bmorelli25** [comment]
run docs-build

**Comment by bmorelli25** [comment]
run docs-build

**Review by bmorelli25 — COMMENTED** [review]
WOOOO!

**Comment by mjwolf** [comment]
Hi @lcawl, ECS 8.16 is going to be release with this stack release. https://github.com/elastic/docs/pull/3112 has most of the doc changes to prepare for this.

Could you update https://github.com/elastic/docs/blob/master/conf.yaml#L1000 to `8.16` in this PR too?

**Pull request merged**
