### PR TITLE
Bumps docs version to 8.9.1

### PR DESCRIPTION
**Pull request by chriscressman**

### CODE REVIEW

**Comment by chriscressman** [comment]
Blocked by https://github.com/elastic/stack-docs/pull/2513

**Comment by chriscressman** [comment]
@elasticmachine run elasticsearch-ci/docs rebuild

**Review by kilfoyle — APPROVED** [review]
LGTM!

**Comment by chriscressman** [comment]
@elasticmachine run elasticsearch-ci/docs rebuild

**Comment by chriscressman** [comment]
@elasticmachine run elasticsearch-ci/docs rebuild

**Pull request merged**
