### PR TITLE
Ruby Client - code snippets

### PR DESCRIPTION
**Pull request by philkra**
This PR is equivalent to https://github.com/elastic/docs/pull/1088 and adds documentation examples for the Ruby client.

/cc @estolfo

### CODE REVIEW

**Comment by philkra** [comment]
Addressed the issues with the examples in https://github.com/elastic/elasticsearch-ruby/pull/719.

**Comment by philkra** [comment]
Jenkins test this please.

**Comment by philkra** [comment]
run elasticsearch-ci/docs

**Comment by nik9000** [comment]
@elasticmachine, run elasticsearch-ci/docs

**Comment by nik9000** [comment]
The build failure looks like a bug on my side. I'll look into it!

**Comment by nik9000** [comment]
> The build failure looks like a bug on my side. I'll look into it!

It turns out it isn't a bug in my code, but a bug in my code is making it hard to find the real problems:
```
INFO:build_docs:asciidoctor: WARNING: ../../../elasticsearch-ruby/examples/docs/asciidoc/setup/install/check_running/3d1ff6097e2359f927c88c2ccdb36252.adoc: line 3: tag '048d8abd42d094bbdcf4452a58ccb35b' not found in include file: /doc/elasticsearch-ruby/examples/docs/spec/check_running_spec.rb
INFO:build_docs:asciidoctor: WARNING: ../../../elasticsearch-ruby/examples/docs/asciidoc/setup/install/check_running/3d1ff6097e2359f927c88c2ccdb36252.adoc: line 3: tag '048d8abd42d094bbdcf4452a58ccb35b' not found in include file: /doc/elasticsearch-ruby/examples/docs/spec/check_running_spec.rb
INFO:build_docs:asciidoctor: WARNING: ../../../elasticsearch-ruby/examples/docs/asciidoc/setup/install/check_running/3d1ff6097e2359f927c88c2ccdb36252.adoc: line 3: tag '048d8abd42d094bbdcf4452a58ccb35b' not found in include file: /doc/elasticsearch-ruby/examples/docs/spec/check_running_spec.rb
INFO:build_docs:asciidoctor: WARNING: ../../../elasticsearch-ruby/examples/docs/asciidoc/setup/install/check_running/3d1ff6097e2359f927c88c2ccdb36252.adoc: line 3: tag '048d8abd42d094bbdcf4452a58ccb35b' not found in include file: /doc/elasticsearch-ruby/examples/docs/spec/check_running_spec.rb
INFO:build_docs:asciidoctor: WARNING: ../../../elasticsearch-ruby/examples/docs/asciidoc/setup/install/check_running/3d1ff6097e2359f927c88c2ccdb36252.adoc: line 3: tag '048d8abd42d094bbdcf4452a58ccb35b' not found in include file: /doc/elasticsearch-ruby/examples/docs/spec/check_running_spec.rb
```

**Comment by philkra** [comment]
thanks Nik, I'll fix the paths

**Comment by philkra** [comment]
Fixed the reference error in https://github.com/elastic/elasticsearch-ruby/pull/720

**Comment by philkra** [comment]
run elasticsearch-ci/docs

**Pull request merged**
