### PR TITLE
Add ECK 2.16

### PR DESCRIPTION
**Pull request by naemono**
This adds the ECK 2.16 branch to the build list. ECK 2.16.0 is planned for release on ~~December 12th.~~

This has been delayed to Dec 19th.

### CODE REVIEW

**Comment by naemono** [comment]
@elastic/docs-repo-owners Could anyone give this a review please? The linked buildkite build did pass after a retry.

**Review by kilfoyle — APPROVED** [review]
LGTM! 🚀

**Comment by naemono** [comment]
> LGTM! 🚀

thank you for the review, but how do I get this merged since the docs build shows failed but actually succeeded?

**Comment by kilfoyle** [comment]
@naemono The docs-build-pr CI check [log](https://buildkite.com/elastic/docs-build-pr/builds/205239#01939cb9-6218-4d21-9d2f-3c9fcc04a7a3) shows this error: 

`WARNING: invalid reference: release-notes-2.16.0`

I'm confused as to why this fails though, because I do see that release-notes-2.16.0 [here](https://github.com/elastic/cloud-on-k8s/blob/2.16/docs/release-notes/2.16.0.asciidoc) in the 2.16 branch.

**Comment by naemono** [comment]
> @naemono The docs-build-pr CI check [log](https://buildkite.com/elastic/docs-build-pr/builds/205239#01939cb9-6218-4d21-9d2f-3c9fcc04a7a3) shows this error:
> 
> `WARNING: invalid reference: release-notes-2.16.0`
> 
> I'm confused as to why this fails though, because I do see that release-notes-2.16.0 file [here](https://github.com/elastic/cloud-on-k8s/blob/2.16/docs/release-notes/2.16.0.asciidoc) in the `cloud-on-k8s` repo's 2.16 branch.

it wasn't originally in that Branch, and that was fixed yesterday so I think the logs you're looking at may be outdated

**Comment by kilfoyle** [comment]
@naemono  Sorry, I missed that the docs build passed on the second run. I've just pushed an empty commit to this PR to relaunch everything, and hopefully that will be the magic we need. :-)

**Pull request merged**
