### PR TITLE
Add source_branch attribute

### PR DESCRIPTION
**Pull request by nik9000**
The `source_branch` attribute should be useful in resolving inter-book
links. We can get this *perfect* when we're running with `--all` because
every book already *has* a branch attribute. When we build with `--doc`
we have to guess. I've added some heuristics that I feal are likely to
guess right most of the time for most folks. I'm not too worried about
guessing wrong *sometimes* because, for the most part, that'll only
break interbook links and lots of folks don't check those locally
anyway. And because we have the pull request tests which run with
`--all` so they'll serve as an accurate backstop.

Relates to #804

### CODE REVIEW

**Comment by nik9000** [comment]
@olksdr I went "full perl" on this one. The only difficult part of this is the regular expression. And the testing.

**Comment by nik9000** [comment]
Oooh good catch past-me!

**Comment by nik9000** [comment]
Wrote a test for that weird case.

**Comment by lcawl** [comment]
When I remove the source_branch attribute from https://github.com/elastic/stack-docs/pull/493,  the Stack Overview still builds successfully.  Therefore, this LGTM

**Comment by nik9000** [comment]
Thanks for reviewing @olksdr!

**Pull request merged**
