### PR TITLE
Update current for 7.9.0 release

### PR DESCRIPTION
**Pull request by lcawl**
This PR updates "current" to 7.9 and changes it from "unreleased" to "released".

--Do not merge this PR until the day of the release!--

### CODE REVIEW

**Comment by jrodewig** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by karenzone** [comment]
I'll work the Logstash Ref and VPR link fixes.

**Comment by karenzone** [comment]
@elasticmachine run elasticsearch-ci/docs rebuild

**Comment by lcawl** [comment]
@elasticmachine run elasticsearch-ci/docs

**Pull request merged**
