### PR TITLE
Bumps current to 8.15.0

### PR DESCRIPTION
**Pull request by KOTungseth**
**Do not merge until release day**

### CODE REVIEW

**Review by lcawl — APPROVED** [review]
LGTM!

**Comment by bmorelli25** [comment]
run docs-build rebuild

**Comment by bmorelli25** [comment]
uh oh... cc @colleenmcginnis 

```

2024-08-07 09:11:22 PDT | INFO:build_docs:Bad cross-document links:
-- | --
  | 2024-08-07 09:11:22 PDT | INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/agent/dotnet/1.x/config-core.html contains broken links to:
  | 2024-08-07 09:11:22 PDT | INFO:build_docs:   - en/kibana/8.15/filters.html#environment-selector
  | 2024-08-07 09:11:22 PDT | INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/agent/dotnet/current/config-core.html contains broken links to:
  | 2024-08-07 09:11:22 PDT | INFO:build_docs:   - en/kibana/8.15/filters.html#environment-selector
  | 2024-08-07 09:11:22 PDT | INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/agent/dotnet/master/config-core.html contains broken links to:
  | 2024-08-07 09:11:22 PDT | INFO:build_docs:   - en/kibana/8.15/filters.html#environment-selector
  | 2024-08-07 09:11:22 PDT | INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/agent/go/1.x/configuration.html contains broken links to:
  | 2024-08-07 09:11:22 PDT | INFO:build_docs:   - en/kibana/8.15/filters.html#environment-selector
  | 2024-08-07 09:11:22 PDT | INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/agent/go/2.x/configuration.html contains broken links to:
  | 2024-08-07 09:11:22 PDT | INFO:build_docs:   - en/kibana/8.15/filters.html#environment-selector
  | 2024-08-07 09:11:22 PDT | INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/agent/go/current/configuration.html contains broken links to:
  | 2024-08-07 09:11:22 PDT | INFO:build_docs:   - en/kibana/8.15/filters.html#environment-selector
  | 2024-08-07 09:11:22 PDT | INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/agent/go/master/configuration.html contains broken links to:
  | 2024-08-07 09:11:22 PDT | INFO:build_docs:   - en/kibana/8.15/filters.html#environment-selector
  | 2024-08-07 09:11:22 PDT | INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/agent/java/1.x/config-core.html contains broken links to:
  | 2024-08-07 09:11:22 PDT | INFO:build_docs:   - en/kibana/8.15/filters.html#environment-selector
  | 2024-08-07 09:11:22 PDT | INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/agent/java/current/config-core.html contains broken links to:
  | 2024-08-07 09:11:22 PDT | INFO:build_docs:   - en/kibana/8.15/filters.html#environment-selector
  | 2024-08-07 09:11:22 PDT | INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/agent/java/master/config-core.html contains broken links to:
  | 2024-08-07 09:11:22 PDT | INFO:build_docs:   - en/kibana/8.15/filters.html#environment-selector
  | 2024-08-07 09:11:22 PDT | INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/agent/nodejs/3.x/configuration.html contains broken links to:
  | 2024-08-07 09:11:22 PDT | INFO:build_docs:   - en/kibana/8.15/filters.html#environment-selector
  | 2024-08-07 09:11:22 PDT | INFO:build_docs:   - en/kibana/8.15/service-overview.html#service-span-duration
  | 2024-08-07 09:11:22 PDT | INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/agent/nodejs/4.x/configuration.html contains broken links to:
  | 2024-08-07 09:11:22 PDT | INFO:build_docs:   - en/kibana/8.15/filters.html#environment-selector
  | 2024-08-07 09:11:22 PDT | INFO:build_docs:   - en/kibana/8.15/service-overview.html#service-span-duration
  | 2024-08-07 09:11:22 PDT | INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/agent/nodejs/current/configuration.html contains broken links to:
  | 2024-08-07 09:11:22 PDT | INFO:build_docs:   - en/kibana/8.15/filters.html#environment-selector
  | 2024-08-07 09:11:22 PDT | INFO:build_docs:   - en/kibana/8.15/service-overview.html#service-span-duration
  | 2024-08-07 09:11:22 PDT | INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/agent/nodejs/master/configuration.html contains broken links to:
  | 2024-08-07 09:11:22 PDT | INFO:build_docs:   - en/kibana/8.15/filters.html#environment-selector
  | 2024-08-07 09:11:22 PDT | INFO:build_docs:   - en/kibana/8.15/service-overview.html#service-span-duration
  | 2024-08-07 09:11:22 PDT | INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/agent/php/1.x/configuration-reference.html contains broken links to:
  | 2024-08-07 09:11:22 PDT | INFO:build_docs:   - en/kibana/8.15/filters.html#environment-selector
  | 2024-08-07 09:11:22 PDT | INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/agent/php/current/configuration-reference.html contains broken links to:
  | 2024-08-07 09:11:22 PDT | INFO:build_docs:   - en/kibana/8.15/filters.html#environment-selector
  | 2024-08-07 09:11:22 PDT | INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/agent/php/master/configuration-reference.html contains broken links to:
  | 2024-08-07 09:11:22 PDT | INFO:build_docs:   - en/kibana/8.15/filters.html#environment-selector
  | 2024-08-07 09:11:22 PDT | INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/agent/python/5.x/configuration.html contains broken links to:
  | 2024-08-07 09:11:22 PDT | INFO:build_docs:   - en/kibana/8.15/filters.html#environment-selector
  | 2024-08-07 09:11:22 PDT | INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/agent/python/6.x/configuration.html contains broken links to:
  | 2024-08-07 09:11:22 PDT | INFO:build_docs:   - en/kibana/8.15/filters.html#environment-selector
  | 2024-08-07 09:11:22 PDT | INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/agent/python/current/configuration.html contains broken links to:
  | 2024-08-07 09:11:22 PDT | INFO:build_docs:   - en/kibana/8.15/filters.html#environment-selector
  | 2024-08-07 09:11:22 PDT | INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/agent/python/master/configuration.html contains broken links to:
  | 2024-08-07 09:11:22 PDT | INFO:build_docs:   - en/kibana/8.15/filters.html#environment-selector
  | 2024-08-07 09:11:22 PDT | INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/agent/ruby/3.x/configuration.html contains broken links to:
  | 2024-08-07 09:11:22 PDT | INFO:build_docs:   - en/kibana/8.15/filters.html#environment-selector
  | 2024-08-07 09:11:22 PDT | INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/agent/ruby/4.x/configuration.html contains broken links to:
  | 2024-08-07 09:11:22 PDT | INFO:build_docs:   - en/kibana/8.15/filters.html#environment-selector
  | 2024-08-07 09:11:22 PDT | INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/agent/ruby/current/configuration.html contains broken links to:
  | 2024-08-07 09:11:22 PDT | INFO:build_docs:   - en/kibana/8.15/filters.html#environment-selector
  | 2024-08-07 09:11:22 PDT | INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/agent/ruby/master/configuration.html contains broken links to:
  | 2024-08-07 09:11:22 PDT | INFO:build_docs:   - en/kibana/8.15/filters.html#environment-selector
  | 2024-08-07 09:11:22 PDT | INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/agent/rum-js/4.x/configuration.html contains broken links to:
  | 2024-08-07 09:11:22 PDT | INFO:build_docs:   - en/kibana/8.15/filters.html#environment-selector
  | 2024-08-07 09:11:22 PDT | INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/agent/rum-js/5.x/configuration.html contains broken links to:
  | 2024-08-07 09:11:22 PDT | INFO:build_docs:   - en/kibana/8.15/filters.html#environment-selector
  | 2024-08-07 09:11:22 PDT | INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/agent/rum-js/current/configuration.html contains broken links to:
  | 2024-08-07 09:11:22 PDT | INFO:build_docs:   - en/kibana/8.15/filters.html#environment-selector
  | 2024-08-07 09:11:22 PDT | INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/agent/rum-js/master/configuration.html contains broken links to:
  | 2024-08-07 09:11:22 PDT | INFO:build_docs:   - en/kibana/8.15/filters.html#environment-selector


```

**Comment by bmorelli25** [comment]
I'm a dummy. https://github.com/elastic/kibana/pull/190061 hasn't been merged yet.

**Comment by colleenmcginnis** [comment]
>uh oh

This is expected because https://github.com/elastic/kibana/pull/190061 isn't merged yet. I'll rerun the build here again after it merges!

**Review by colleenmcginnis — APPROVED** [review]
Fixed! ✨

**Pull request merged**
