### PR TITLE
Buildkite PR job for assembling docs

### PR DESCRIPTION
**Pull request by TrushynAliaksandr**
This PR introduces a Buildkite job to build pull requests. It replaces and combine the following Jenkins job:
* product repositories job Jenkins Job [template](https://github.com/elastic/infra/blob/master/ci/jjb/elasticsearch-ci/globals/templates/elastic-docs/pull-requests.yml)
* elastic/docs Jenkins [PR job](https://github.com/elastic/infra/blob/master/ci/jjb/elasticsearch-ci/defs/elastic-docs/pull-requests.yml#L114-L190)

### General approach

In the Jenkins world, we setup a dedicated job per repository with the job dsl coming from a template. We took a different approach in Buildkite, and instead setup a single Buildkite job that gets triggered for every PR builds on any of the docs product repo or the elastic/docs repo. This allows us to keep things tidy in Buildkite ( a single job) and limit considerably the amount of CI code to write in any product repository (see discussion on this approach [here](https://github.com/elastic/docs-projects/issues/136#issuecomment-1763735623)).

There are some downsides to this approach however:
* going to Buildkite build page looking for a specific build for a PR is not straight forward - it can be done by adding GET params to the builds url. For eg, to view the builds PR 3366 in `elastic/observability-docs`, we can visit the following URL: https://buildkite.com/elastic/docs-build-pr/builds?meta_data[repo_pr]=observability-docs_3366

* Since the same job is used for any PR in any of the product repositories, we allow concurrent builds of that job (otherwise, we could only run a single doc build at a time for any of the product repo). I have not seen/experienced/validated this yet, but we could run into scenarios where the same PR with 2 docs builds triggered in a short time frame try to push to the same preview branch and <insert some problem>. 

### Docs repo configuration 

We use the [Buildkite PR bot](https://docs.elastic.dev/ci/configuring-pull-requests-for-buildkite) in a non-conventional manner to achieve the above result:
* we use an "org-wide" configuration file stored in the `master` branch of `elastic/docs` - [here](https://github.com/elastic/docs/blob/master/.buildkite/pull-requests.org-wide.json) (That file is not read in other branches).
* for all the products repositories, we leverage the `"always_trigger_branch":true` option. This is currently set to this branch while under development.
* for the `elastic:docs` repository, we use the default `"always_trigger_branch":false` option - since the build logic is stored within the `elastic:docs` repo - this is what would allow us to test out changes to the build logic itself.

Finally, the Buildkite PR bot allows for changes detections at certain path - this allows us to not trigger a PR build for every change in every docs repo, but only target doc changes. 

With the above said, we have 3 configuration blobs in the PR bot config:
* **product docs** repo that should build for any change in the repo should be added [here](https://github.com/elastic/docs/blob/master/.buildkite/pull-requests.org-wide.json#L21-L24)
* **product docs** repo that should build only when files within the `./docs` folder should be added [here](https://github.com/elastic/docs/blob/master/.buildkite/pull-requests.org-wide.json#L48-L50)
* config changes to `elastic/docs` is controlled [here](https://github.com/elastic/docs/blob/master/.buildkite/pull-requests.org-wide.json#L53-L70)

The below config options have been configured for all of the above repositories:
* **run docs-build**
* **run docs-build** `rebuild`
* **run docs-build** `warnlinkcheck`
* **run docs-build** `skiplinkcheck` (takes precedence over the warnlinkcheck option)

### PR job setup

When a docs PR job is opened / commented on, the Buildkite PR bot will trigger a [docs-build-pr](https://buildkite.com/elastic/docs-build-pr) job, passing a few key env variables about the PR.  The build script [checks out](https://github.com/elastic/docs/pull/2804/files#diff-5ea8cc5083302320861aeb6d2dc6d73f688d94c1ed975a3c4bd1ad351cd23a74R36-R52) that specific branch of the repository locally and references it in the build argument leveraging the `--sub-dir` option.

Similarly to Jenkins, PR on the `elastic/docs` repo always trigger a full `rebuild`.

PR are annotated with a link to the job preview and diff upon successful build - see example [here](https://github.com/elastic/observability-docs/pull/3366#issuecomment-1813051017).

Similar to other Buildkite job, docs preview changes are pushed to the <repo>_bk_<PR> branch until the migration is complete.

### pre/post command hooks

We're leveraging theses the pre-command hook to setup the build commit status to `pending` and the post-commit one to `success` and `failure`. At this time, we're re-using the GITHUB token from the `preview-cleaner` job that has sufficient permissions to do such API calls.

All of the perms (to clone repo, commit) are tied to elasticmachine - I suspect this may have to change at some point in the future, but that's the current setup.

## Jenkins/Buildkite comparison

Example of jobs that ran, and the differences between Jenkins and Buildkite, and the diff between the built-docs branches.

* https://github.com/elastic/observability-docs/pull/3366 - [diff](https://github.com/elastic/built-docs/compare/observability-docs_bk_3366..observability-docs_3366)
* https://github.com/elastic/tech-content/pull/382 - [diff](https://github.com/elastic/built-docs/compare/tech-content_bk_382..tech-content_382)
* https://github.com/elastic/docs/pull/2833 - [diff](https://github.com/elastic/built-docs/compare/docs_bk_2833..docs_2833)
* https://github.com/elastic/observability-docs/pull/3373 - [diff](https://github.com/elastic/built-docs/compare/observability-docs_bk_3373..observability-docs_3373)

Note - on the docs changes in the `docs` repo, we're seeing images conflicts and changes - see convo about it [here](https://elastic.slack.com/archives/C05SZ9CGB19/p1699984533230979?thread_ts=1699973252.260879&cid=C05SZ9CGB19).

### CODE REVIEW

**Comment by TrushynAliaksandr** [comment]
To do:

- Add set_commit_status to the master: elastic/docs repository and think about how we can get the status after the end of the pipeline (now only the pending status is set)

- Add other required repositories to the org-wide config and create webhook for each

**Comment by nkammah** [comment]
This does not seem to work as expected - see this [build](https://buildkite.com/elastic/docs-build/builds/183#018b9ccb-c7b5-4b62-a676-c69f755daba8) - the preview URL was set to
 
`https://docs_bk_false.docs-preview.app.elstc.co/diff`
           instead of 
`https://docs_bk_2805.docs-preview.app.elstc.co/diff`

**Comment by nkammah** [comment]
run docs-build rebuild warnlinkcheck

**Comment by nkammah** [comment]
Closing this PR - will open a new one under my name.

**Pull request closed without merging**
