### PR TITLE
Update docs build for 7.x with changed build-tools organization

### PR DESCRIPTION
**Pull request by breskeby**
This is the 7.x specific fix for https://github.com/elastic/docs/pull/2127 
We have back ported the build tool organisation changes to 7.x and this PR adopts this change.

### CODE REVIEW

**Comment by breskeby** [comment]
checking the failure

**Comment by breskeby** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by gtback** [comment]
Looks like the error is with building the 7.x branch:

```
09:02:55 INFO:build_docs:asciidoctor: ERROR: dependencies-versions.asciidoc: line 6: include file not found: /tmp/docsbuild/npkB8LhlHt/elasticsearch/buildSrc/version.properties
```

Taking a look at the [`dependencies-versions.asciidoc`](https://github.com/elastic/elasticsearch/blob/7.x/docs/reference/dependencies-versions.asciidoc) file, it seems like it's referring to a variable `dependencies-dir`. I think it needs to be update [here](https://github.com/elastic/elasticsearch/blob/7.x/docs/reference/index.asciidoc#L7) (and this seems like the only use of this variable that I can find, so it's not likely to break anything else 🤞🏻.

**Comment by gtback** [comment]
cc: @elastic/es-docs

**Comment by breskeby** [comment]
pushed a fix.

**Comment by breskeby** [comment]
@elasticmachine run elasticsearch-ci/docs

**Review by jrodewig — APPROVED** [review]
LGTM. I'm merging this in as the docs build is currently broken.

**Pull request merged**
