### PR TITLE
Switch headings to aktiv grotesk

### PR DESCRIPTION
**Pull request by nik9000**
We'd intended to do this a long time ago.

Relates to #1081.

### CODE REVIEW

**Comment by nik9000** [comment]
@brianjolly, please have a look at the preview for this one. All of the headers look so big!

**Comment by brianjolly** [comment]
Hi @nik9000 , we could pick up the font sizes from the redesign site. Lets see how this looks:
```
  h1 {
-    font-size: 44px;
+    font-size: 36px;
...
  h3 {
-     font-size: 26px;
+    font-size: 22px;
```

**Comment by nik9000** [comment]
@brianjolly I pushed an update with that style. I picker 29px for the h2 font size because it is half way between. We use a fair bit of h1-h3.

**Comment by nik9000** [comment]
@elasticmachine, run elasticsearch-ci/docs

**Pull request merged**
