### PR TITLE
Move APM Guide docs to observability-docs repo

### PR DESCRIPTION
**Pull request by bmorelli25**
For https://github.com/elastic/obs-docs-projects/issues/216

### CODE REVIEW

**Comment by bmorelli25** [comment]
@elasticmachine, run elasticsearch-ci/docs rebuild

**Comment by bmorelli25** [comment]
@elasticmachine, run elasticsearch-ci/docs rebuild

**Comment by bmorelli25** [comment]
@colleenmcginnis. Based on a new error, I've determined that the `apm-server` repository is a dependency of the Observability Guide in version 7.15. I did not test previous versions, but it's likely that this dependency exists in at least part or all of the versions between 7.15 and 7.9.

For this reason, I re-added the `apm-server` dependency for these versions in 943af47. After we get this PR building, we can probably copy the needed files to the `observability-docs` repository and remove this dependency again.

**Comment by bmorelli25** [comment]
@elasticmachine, run elasticsearch-ci/docs rebuild

**Comment by bmorelli25** [comment]
@elasticmachine, run elasticsearch-ci/docs rebuild

**Review by colleenmcginnis — APPROVED** [review]
✨

**Pull request merged**
