### PR TITLE
Switch RUM apm agent to direct_html

### PR DESCRIPTION
**Pull request by nik9000**
direct_html is faster and more customizable. It is the future.

### CODE REVIEW

**Comment by nik9000** [comment]
@bmorelli25, I'm using this PR to make a preview which I'll check for accuracy.

**Comment by bmorelli25** [comment]
Is the [diff](http://docs_1634.docs-preview.app.elstc.co/diff) supposed to be that big? I've been clicking around a bit, but can't see anything that looks wrong.

**Comment by nik9000** [comment]
The diff from the preview is a line by line diff. My diff that I make on my
laptop parses the html then runs the diff. So, yeah, I expect a big diff in
the preview but for the one I run to be much smaller.

**Comment by nik9000** [comment]
When I run the diff with the [diff tool](https://github.com/elastic/docs/blob/master/integtest/html_diff) it is empty. But the tool has a bunch of "normalize the html" stuff that the docs-preview's diff doesn't have.

**Comment by nik9000** [comment]
So I'm ready to merge this anytime you are @bmorelli25 .

**Comment by bmorelli25** [comment]
Opened https://github.com/elastic/apm-agent-rum-js/pull/538 to update the build script in the RUM repo.

**Pull request merged**
