### PR TITLE
Adds shared attribute for the Swimlane connector

### LINKED ISSUE #2151: Adds shared attribute for the Swimlane connector
A new Swimlane connector for cases and alerts was introduced to the Security solution in 7.14 and I’d like to add a new attribute for that connector name. 

Related to: https://github.com/elastic/security-docs/issues/779

cc: @jmikell821

### PR DESCRIPTION
**Pull request by nastasha-solomon**
Resolves #2151.

### CODE REVIEW

**Review by jmikell821 — APPROVED** [review]
LGTM!

**Review by gtback — APPROVED** [review]

**Comment by gtback** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by gtback** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by leathekd** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by gtback** [comment]
@elasticmachine run self-test

**Pull request merged**
