### PR TITLE
Use `*stackcurrent` for APM Guide

### PR DESCRIPTION
**Pull request by bmorelli25**
Not sure how I missed this. Updating for 7.16 docs.

### CODE REVIEW

**Review by dedemorton — APPROVED** [review]
LGTM

**Review by gtback — APPROVED** [review]
LGTM!

**Comment by bmorelli25** [comment]
@elasticmachine, run elasticsearch-ci/docs

**Comment by bmorelli25** [comment]
@elasticmachine, run elasticsearch-ci/docs

**Pull request merged**
