### PR TITLE
ESS - Change current to MS-62

### PR DESCRIPTION
**Pull request by kilfoyle**
This changes "current" for the Cloud ESS docs to MS-62.

### CODE REVIEW

**Review by gtback — APPROVED** [review]

**Comment by kilfoyle** [comment]
@gtback Brilliant! Just one line to change.
Thanks for pushing this!

**Comment by gtback** [comment]
@kilfoyle I'm not sure why the build is failing (it looks like it's broken links). I'm not sure if something has changed in the cloud repo since your initial commit, or if it's related to the changes I just made. Do you have a chance to take a look?

```
16:56:03 INFO:build_docs:Bad cross-document links:
16:56:03 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/app-search/7.10/installation.html contains broken links to:
16:56:03 INFO:build_docs:   - en/cloud/current/ec-getting-started-solutions.html#ec-getting-started-enterprise-search
16:56:03 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/app-search/7.11/installation.html contains broken links to:
16:56:03 INFO:build_docs:   - en/cloud/current/ec-getting-started-solutions.html#ec-getting-started-enterprise-search
16:56:03 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/app-search/7.12/installation.html contains broken links to:
16:56:03 INFO:build_docs:   - en/cloud/current/ec-getting-started-solutions.html#ec-getting-started-enterprise-search
16:56:03 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/app-search/7.13/installation.html contains broken links to:
16:56:03 INFO:build_docs:   - en/cloud/current/ec-getting-started-solutions.html#ec-getting-started-enterprise-search
16:56:03 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/app-search/7.14/installation.html contains broken links to:
16:56:03 INFO:build_docs:   - en/cloud/current/ec-getting-started-solutions.html#ec-getting-started-enterprise-search
16:56:03 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/app-search/7.15/installation.html contains broken links to:
16:56:03 INFO:build_docs:   - en/cloud/current/ec-getting-started-solutions.html#ec-getting-started-enterprise-search
16:56:03 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/app-search/7.7/installation.html contains broken links to:
16:56:03 INFO:build_docs:   - en/cloud/current/ec-getting-started-solutions.html#ec-getting-started-enterprise-search
16:56:03 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/app-search/7.8/installation.html contains broken links to:
16:56:03 INFO:build_docs:   - en/cloud/current/ec-getting-started-solutions.html#ec-getting-started-enterprise-search
16:56:03 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/app-search/7.9/installation.html contains broken links to:
16:56:03 INFO:build_docs:   - en/cloud/current/ec-getting-started-solutions.html#ec-getting-started-enterprise-search
16:56:03 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/app-search/7.x/installation.html contains broken links to:
16:56:03 INFO:build_docs:   - en/cloud/current/ec-getting-started-solutions.html#ec-getting-started-enterprise-search
16:56:03 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/app-search/current/installation.html contains broken links to:
16:56:03 INFO:build_docs:   - en/cloud/current/ec-getting-started-solutions.html#ec-getting-started-enterprise-search
16:56:03 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/app-search/master/installation.html contains broken links to:
16:56:03 INFO:build_docs:   - en/cloud/current/ec-getting-started-solutions.html#ec-getting-started-enterprise-search
16:56:03 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/cloud-heroku/current/ech-restrictions.html contains broken links to:
16:56:03 INFO:build_docs:   - en/kibana/7.14/agent-configuration.html[APM
16:56:03 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/cloud-heroku/latest/ech-restrictions.html contains broken links to:
16:56:03 INFO:build_docs:   - en/kibana/7.14/agent-configuration.html[APM
16:56:03 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/cloud/current/ec-restrictions.html contains broken links to:
16:56:03 INFO:build_docs:   - en/kibana/7.14/agent-configuration.html[APM
16:56:03 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/cloud/latest/ec-restrictions.html contains broken links to:
16:56:03 INFO:build_docs:   - en/kibana/7.14/agent-configuration.html[APM
16:56:03 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/enterprise-search/7.10/installation.html contains broken links to:
16:56:03 INFO:build_docs:   - en/cloud/current/ec-getting-started-solutions.html#ec-getting-started-enterprise-search
16:56:03 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/enterprise-search/7.11/installation.html contains broken links to:
16:56:03 INFO:build_docs:   - en/cloud/current/ec-getting-started-solutions.html#ec-getting-started-enterprise-search
16:56:03 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/enterprise-search/7.12/installation.html contains broken links to:
16:56:03 INFO:build_docs:   - en/cloud/current/ec-getting-started-solutions.html#ec-getting-started-enterprise-search
16:56:03 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/enterprise-search/7.13/installation.html contains broken links to:
16:56:03 INFO:build_docs:   - en/cloud/current/ec-getting-started-solutions.html#ec-getting-started-enterprise-search
16:56:03 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/enterprise-search/7.14/installation.html contains broken links to:
16:56:03 INFO:build_docs:   - en/cloud/current/ec-getting-started-solutions.html#ec-getting-started-enterprise-search
16:56:03 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/enterprise-search/7.15/installation.html contains broken links to:
16:56:03 INFO:build_docs:   - en/cloud/current/ec-getting-started-solutions.html#ec-getting-started-enterprise-search
16:56:03 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/enterprise-search/7.7/installation.html contains broken links to:
16:56:03 INFO:build_docs:   - en/cloud/current/ec-getting-started-solutions.html#ec-getting-started-enterprise-search
16:56:03 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/enterprise-search/7.8/installation.html contains broken links to:
16:56:03 INFO:build_docs:   - en/cloud/current/ec-getting-started-solutions.html#ec-getting-started-enterprise-search
16:56:03 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/enterprise-search/7.9/installation.html contains broken links to:
16:56:03 INFO:build_docs:   - en/cloud/current/ec-getting-started-solutions.html#ec-getting-started-enterprise-search
16:56:03 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/enterprise-search/7.x/installation.html contains broken links to:
16:56:03 INFO:build_docs:   - en/cloud/current/ec-getting-started-solutions.html#ec-getting-started-enterprise-search
16:56:03 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/enterprise-search/current/installation.html contains broken links to:
16:56:03 INFO:build_docs:   - en/cloud/current/ec-getting-started-solutions.html#ec-getting-started-enterprise-search
16:56:03 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/enterprise-search/master/installation.html contains broken links to:
16:56:03 INFO:build_docs:   - en/cloud/current/ec-getting-started-solutions.html#ec-getting-started-enterprise-search
16:56:03 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/workplace-search/7.10/workplace-search-install.html contains broken links to:
16:56:03 INFO:build_docs:   - en/cloud/current/ec-getting-started-solutions.html#ec-getting-started-enterprise-search
16:56:03 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/workplace-search/7.11/workplace-search-install.html contains broken links to:
16:56:03 INFO:build_docs:   - en/cloud/current/ec-getting-started-solutions.html#ec-getting-started-enterprise-search
16:56:03 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/workplace-search/7.12/workplace-search-install.html contains broken links to:
16:56:03 INFO:build_docs:   - en/cloud/current/ec-getting-started-solutions.html#ec-getting-started-enterprise-search
16:56:03 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/workplace-search/7.13/workplace-search-install.html contains broken links to:
16:56:03 INFO:build_docs:   - en/cloud/current/ec-getting-started-solutions.html#ec-getting-started-enterprise-search
16:56:03 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/workplace-search/7.14/workplace-search-install.html contains broken links to:
16:56:03 INFO:build_docs:   - en/cloud/current/ec-getting-started-solutions.html#ec-getting-started-enterprise-search
16:56:03 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/workplace-search/7.15/workplace-search-install.html contains broken links to:
16:56:03 INFO:build_docs:   - en/cloud/current/ec-getting-started-solutions.html#ec-getting-started-enterprise-search
16:56:03 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/workplace-search/7.7/workplace-search-install.html contains broken links to:
16:56:03 INFO:build_docs:   - en/cloud/current/ec-getting-started-solutions.html#ec-getting-started-enterprise-search
16:56:03 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/workplace-search/7.8/workplace-search-install.html contains broken links to:
16:56:03 INFO:build_docs:   - en/cloud/current/ec-getting-started-solutions.html#ec-getting-started-enterprise-search
16:56:03 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/workplace-search/7.9/workplace-search-install.html contains broken links to:
16:56:03 INFO:build_docs:   - en/cloud/current/ec-getting-started-solutions.html#ec-getting-started-enterprise-search
16:56:03 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/workplace-search/7.x/workplace-search-install.html contains broken links to:
16:56:03 INFO:build_docs:   - en/cloud/current/ec-getting-started-solutions.html#ec-getting-started-enterprise-search
16:56:03 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/workplace-search/current/workplace-search-install.html contains broken links to:
16:56:03 INFO:build_docs:   - en/cloud/current/ec-getting-started-solutions.html#ec-getting-started-enterprise-search
16:56:03 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/workplace-search/master/workplace-search-install.html contains broken links to:
16:56:03 INFO:build_docs:   - en/cloud/current/ec-getting-started-solutions.html#ec-getting-started-enterprise-search
```

**Comment by kilfoyle** [comment]
@gtback  It looks like it's related to changes from https://github.com/elastic/cloud/pull/87391  which removed the page `ec-getting-started-solutions.html`.  

Here's the link on the Enterprise Search [Installation page](https://www.elastic.co/guide/en/enterprise-search/current/installation.html).
Screen Shot 2021-09-01 at 8 28 12 PM

I'll open a PR for the Enterprise Search, App Search, and Workplace Search docs.

CC @alaudazzi

**Comment by gtback** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by kilfoyle** [comment]
Looking better!
Screen Shot 2021-09-02 at 11 15 11 AM

**Comment by kilfoyle** [comment]
@elasticmachine run elasticsearch-ci/docs

**Pull request merged**
