### PR TITLE
Add ECK 2.11

### PR DESCRIPTION
**Pull request by naemono**
This adds the ECK 2.11 branch to the build list. ECK 2.11.0 is planned for release on January 9th.

### CODE REVIEW

**Review by kilfoyle — APPROVED** [review]
LGTM! 🚀

**Comment by naemono** [comment]
@elastic/docs-repo-owners Since the 2.11/8.12 release is tomorrow, I'm needing to merge this PR today. Could someone with write access handle that for me please? Thanks much!

**Comment by kilfoyle** [comment]
@elasticmachine run docs-build

**Comment by kilfoyle** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by naemono** [comment]
Thanks @kilfoyle , that wasn't simple. 😬

**Comment by kilfoyle** [comment]
My pleasure @naemono! I was a little confused about those CI checks but I'm glad everything is green and merged. :-)

**Pull request merged**
