### PR TITLE
Change current to MS 59

### PR DESCRIPTION
**Pull request by shaunschembri**
This PR changes current to MS 59 for ESS.

### CODE REVIEW

**Review by vogxn — APPROVED** [review]
LGTM

**Comment by shaunschembri** [comment]
Build is failing with broken links
```
08:56:00 INFO:build_docs:Bad cross-document links:
08:56:00 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/cloud-heroku/current/ech-enable-logging-and-monitoring.html contains broken links to:
08:56:00 INFO:build_docs:   - en/elasticsearch/reference/7.13/xpack-security-audit-logging.html
08:56:00 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/cloud-heroku/latest/ech-enable-logging-and-monitoring.html contains broken links to:
08:56:00 INFO:build_docs:   - en/elasticsearch/reference/7.13/xpack-security-audit-logging.html
08:56:00 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/cloud/current/ec-enable-logging-and-monitoring.html contains broken links to:
08:56:00 INFO:build_docs:   - en/elasticsearch/reference/7.13/xpack-security-audit-logging.html
08:56:00 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/cloud/current/ec-release-notes-2021-06-15.html contains broken links to:
08:56:00 INFO:build_docs:   - en/kibana/7.13/7.12
08:56:00 INFO:build_docs:   - en/kibana/7.13/7.12/managing-saved-objects.html
08:56:00 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/cloud/latest/ec-enable-logging-and-monitoring.html contains broken links to:
08:56:00 INFO:build_docs:   - en/elasticsearch/reference/7.13/xpack-security-audit-logging.html
08:56:00 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/cloud/latest/ec-release-notes-2021-06-15.html contains broken links to:
08:56:00 INFO:build_docs:   - en/kibana/7.13/7.12
08:56:00 INFO:build_docs:   - en/kibana/7.13/7.12/managing-saved-objects.html
08:56:00 INFO:build_docs:  Kibana [master]: src/core/public/doc_links/doc_links_service.ts contains broken links to:
08:56:00 INFO:build_docs:   - en/machine-learning/master/ml-dfanalytics-evaluate.html#ml-dfanalytics-roc
```

**Comment by alaudazzi** [comment]
Broken links to Kibana should be OK as soon as https://github.com/elastic/kibana/pull/104380 is merged.

**Comment by alaudazzi** [comment]
Broken links in `ec-ce-enable-logging-and-monitoring.asciidoc` should be OK when #84248 gets merged.

**Comment by alaudazzi** [comment]
Broken links in `feature.asciidoc` should be OK when #84250 gets merged.

**Comment by alaudazzi** [comment]
@elasticmachine run elasticsearch-ci/docs

**Pull request merged**
