### PR TITLE
Use the "version" rather than "branch" in file paths

### PR DESCRIPTION
**Pull request by gtback**
There's an existing method to give each "branch" a "title". The title corresponds to the "name" of the version, in cases where it doesn't match the name of the branch itself, and the "title" already appears in the version dropdown. This change extends that to use the version name ("title") in the URL.

Future work will better distinguish between "branches" and "versions" in cases where they aren't the same.

---

To use this, put a `{ branch-name: version-name }` into the `branches` list of a book in conf.yaml. All other places where you would put a branch (like `live` and `current`) should continue to use the branch name (not the version name), but I plan to make further enhancements to make this more straighforward.

---

Related to https://github.com/elastic/docs/issues/1850

### CODE REVIEW

**Comment by nrichers** [comment]
@gtback I tried this functionality out, but I get this error: 

```
INFO:build_docs:Current branch <2.6> is not in <branches> in book <Elastic Cloud Enterprise - Elastic Cloud on your Infrastructure> at lib/ES/Book.pm line 117.
```

Here's the diff for what I added:

```
diff --git a/conf.yaml b/conf.yaml
index bbe0f1e..b297367 100644
--- a/conf.yaml
+++ b/conf.yaml
@@ -703,8 +703,8 @@ contents:
             prefix:     en/cloud-enterprise
             tags:       CloudEnterprise/Reference
             subject:    ECE
-            current:    2.5
-            branches:   [ 2.5, 2.4, 2.3, 2.2, 2.1, 2.0, 1.1, 1.0 ]
+            current:    2.6
+            branches:   [ {'release-ms-41': 2.6}, 2.5, 2.4, 2.3, 2.2, 2.1, 2.0, 1.1, 1.0 ]
             index:      docs/cloud-enterprise/index.asciidoc
             chunk:      2
             private:    1
@@ -720,6 +720,7 @@ contents:
                 repo:   cloud-assets
                 path:   docs
                 map_branches: &mapCloudEceToCloudAssets
+                  2.6: master
                   2.5: master
                   2.4: master
                   2.3: master
@@ -733,6 +734,7 @@ contents:
                 repo:   clients-team
                 path:   docs/examples/elastic-cloud/php
                 map_branches: &mapCloudEceToClientsTeam
+                  2.6: master
                   2.5: master
                   2.4: master
                   2.3: master
```

**Comment by gtback** [comment]
@nrichers how does this sound?

---

To use this, put a `{ branch-name: version-name }` into the `branches` list of a book in conf.yaml. All other places where you would put a branch (like `live` and `current`) should continue to use the branch name (not the version name), but I plan to make further enhancements to make this more straighforward.

---

**Comment by nrichers** [comment]
> @nrichers how does this sound?
> 
> To use this, put a `{ branch-name: version-name }` into the `branches` list of a book in conf.yaml. All other places where you would put a branch (like `live` and `current`) should continue to use the branch name (not the version name), but I plan to make further enhancements to make this more straighforward.

Yes, if you could add this under a new heading in the section "Building documentation," that would be great! Likely with a new subheading, say, "Need to build versions instead of branches?" or "Building versions where branch names don't match up" or whatever seem right to you.

**Comment by nrichers** [comment]
@gtback One other Q ... what happens with these mappings, do they map to version or the branch? 

image

**Comment by nrichers** [comment]
Just got this to work:

image

This was the diff:

```
diff --git a/conf.yaml b/conf.yaml
index bbe0f1e..34d0732 100644
--- a/conf.yaml
+++ b/conf.yaml
@@ -703,8 +703,8 @@ contents:
             prefix:     en/cloud-enterprise
             tags:       CloudEnterprise/Reference
             subject:    ECE
-            current:    2.5
-            branches:   [ 2.5, 2.4, 2.3, 2.2, 2.1, 2.0, 1.1, 1.0 ]
+            current:    release-ms-41
+            branches:   [ {'release-ms-41': 2.6}, 2.5, 2.4, 2.3, 2.2, 2.1, 2.0, 1.1, 1.0 ]
             index:      docs/cloud-enterprise/index.asciidoc
             chunk:      2
             private:    1
@@ -720,6 +720,7 @@ contents:
                 repo:   cloud-assets
                 path:   docs
                 map_branches: &mapCloudEceToCloudAssets
+                  release-ms-41: master
                   2.5: master
                   2.4: master
                   2.3: master
@@ -733,6 +734,7 @@ contents:
                 repo:   clients-team
                 path:   docs/examples/elastic-cloud/php
                 map_branches: &mapCloudEceToClientsTeam
+                  release-ms-41: master
                   2.5: master
                   2.4: master
                   2.3: master
```

Not sure if everything else works,  but initial testing is promising.

**Comment by gtback** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by gtback** [comment]
Had to fix one more broken link in Kibana: elastic/kibana#73552

**Pull request merged**
