### PR TITLE
Remove unused docs constants

### PR DESCRIPTION
**Pull request by przemekwitek**
This PR removes constants that are not used anywhere.

Relates https://github.com/elastic/elasticsearch/issues/59947

### CODE REVIEW

**Comment by droberts195** [comment]
I am not sure you can merge this.  Old versions of the docs will reference the constant you've removed, and it looks like this repo doesn't have a separate branch for each stack minor release.  I think merging this would break the docs builds for 7.6, 7.7, 7.8 and 7.9.

**Comment by przemekwitek** [comment]
> I am not sure you can merge this. Old versions of the docs will reference the constant you've removed, and it looks like this repo doesn't have a separate branch for each stack minor release. I think merging this would break the docs builds for 7.6, 7.7, 7.8 and 7.9.

Actually these constants were *not* used in out evaluate `asciidoc` before my renaming PR. Still, you may be right that they were used at some point (for at least one minor release) and it's better not to touch them.
Maybe @lcawl will be able to confirm.

**Comment by gtback** [comment]
@lcawl would know for sure. We also have an open issue (#220) to make the build fail for undefined attributes.

**Comment by lcawl** [comment]
@droberts195 is right.  It's used in pages like this: https://www.elastic.co/guide/en/machine-learning/7.6/ml-dfa-overview.html and https://www.elastic.co/guide/en/machine-learning/7.6/ml-dfanalytics-evaluate.html

**Comment by lcawl** [comment]
You're also right that this repo isn't versioned. When there has been a significant change in the shared attributes, we've split a new version of that file (e.g. around 6.2 we split off https://github.com/elastic/docs/blob/master/shared/attributes62.asciidoc), but I don't think this particular change warrants that.

**Comment by gtback** [comment]
At most, I think we can add a comment that these attributes aren't in use after 7.6. We don't regularly rebuild the 7.6 docs, and aren't making changes to them anymore, but we will occasionally rebuild all the docs, and the 7.6 docs will be "broken" (at least, these strings will be missing) once that happens.

**Comment by przemekwitek** [comment]
> We don't regularly rebuild the 7.6 docs, and aren't making changes to them anymore, but we will occasionally rebuild all the docs, and the 7.6 docs will be "broken" (at least, these strings will be missing) once that happens.

Thanks for explanation. Of course, I'm not going to risk breaking the docs. Let's just drop this PR altogether.

**Pull request closed without merging**
