### PR TITLE
Adds the MS31 build to ESS and Heroku books

### PR DESCRIPTION
**Pull request by kellyemurphy**
Just adding the build, leaving current as MS28 for now.

### CODE REVIEW

**Comment by nrichers** [comment]
jenkins test this please

**Comment by nrichers** [comment]
@nik9000 not urgent, but we're seeing an odd error on this PR even after rerunning the tests and flipping the order of the branches to match our newest-first convention: 

```
00:13:04 INFO:build_docs:Error executing: git archive --format=tar -o /tmp/docsbuild/pUxOopPCng/clients-team/.temp_git_archive.tar release-ms-31 examples/elastic-cloud/php in GIT_DIR /docs_build/.repos/clients-team.git
```

This would look related to recent client docs changes (the ones you helped with for PhilipK), _except_ those currently don't live anywhere except the `master` branch of the Cloud repo, which we don't build. 

Any ideas for what we might need to change here?

**Comment by nik9000** [comment]
> Any ideas for what we might need to change here?

On [this](https://github.com/elastic/docs/pull/1500/files#diff-4a701a5adb4359c6abf9b8e1cb38819fR639-R640) list you should add an entry for the new branch, mapping it to master. Unless they want to make a new branch on the clients-team repo which I suspect they don't.

**Comment by kellyemurphy** [comment]
Hopefully the changes from the [Cloud PR](https://github.com/elastic/cloud/pull/45605) will make the links good.

**Pull request merged**
