### PR TITLE
Update docs for ESS to ms-57 branch

### PR DESCRIPTION
**Pull request by Z3r0Sum**
This PR changes current to MS 57 for ESS for the new release and removed the older MS 56 release.

### CODE REVIEW

**Review by jihun-cho — APPROVED** [review]
LGTM!

**Comment by jihun-cho** [comment]
Hi @elastic/docs We tried to release ms-57 docs but the build failed with broken links.
Could you have a look into this?

**Comment by kilfoyle** [comment]
@elasticmachine update branch

**Comment by kilfoyle** [comment]
Thanks for letting us know! I am investigating, and I will merge this PR once I get a fix in.

**Comment by kilfoyle** [comment]
MS-57 Release Notes docs are live now: https://www.elastic.co/guide/en/cloud/current/ec-release-notes-2021-05-25.html
@Z3r0Sum and @jihun-cho  thanks for creating this PR!

**Pull request merged**
