### PR TITLE
Updates conf.yaml refs to include 8.10 branch

### PR DESCRIPTION
**Pull request by benironside**
This PR adds 8.10 branches to the conf.yaml file.

### CODE REVIEW

**Comment by jrodewig** [comment]
Hey @benironside! Can you update or rebase this branch to include changes from https://github.com/elastic/docs/pull/2742?

We'll want to add the 8.10 branch for that new book as well.

**Comment by lcawl** [comment]
The current build error:

> 10:51:12 INFO:build_docs:Error executing: git archive --format=tar -o /tmp/docsbuild/aFUKK6lgkb/elasticsearch-php/.temp_git_archive.tar 8.10 docs/examples in GIT_DIR /docs_build/.repos/elasticsearch-php.git

... indicates that this repo doesn't have an 8.10 branch yet: https://github.com/elastic/elasticsearch-php

To solve that error, we can update the `conf.yaml` to temporarily remove that branch for the PHP client book, and/or ask the clients team how soon they'll create the missing branch

**Comment by benironside** [comment]
Thanks @jrodewig , I added the content from #2742 and added the 8.10 branch reference to the new item.
Thanks @lcawl , I reached out to the clients team about the missing branch.

Appreciate your help!

**Comment by benironside** [comment]
@elasticmachine run elasticsearch-ci/docs rebuild

**Comment by jrodewig** [comment]
Hey @benironside — I pushed [`3978c60` (#2743)](https://github.com/elastic/docs/pull/2743/commits/3978c60c868f0f7b3fa599ab12e10278ecfd4018) to remove the 8.10 branch for the ES PHP client. That'll unblock this PR.

**Comment by benironside** [comment]
@elasticmachine run elasticsearch-ci/docs rebuild

**Comment by lcawl** [comment]
The current build errors are ones I can recreate locally by checking out 8.10 and building the security guide:

> 04:40:57 INFO:build_docs:
04:40:57 INFO:build_docs:asciidoctor: ERROR: detections/prebuilt-rules/downloadable-packages/8-10-1/prebuilt-rules-8-10-1-appendix.asciidoc: line 46: include file not found: /tmp/docsbuild/8ytzuFdx36/security-docs/docs/detections/prebuilt-rules/downloadable-packages/8-10-1/prebuilt-rule-8-10-1-suspicious-network-connection-attempt-by-root.asciidoc
04:40:57 INFO:build_docs:asciidoctor: WARNING: invalid reference: enumerating-domain-trusts-via-nltest.exe

Per discussion with @benironside these seem to be caused by problems in [https://github.com/elastic/security-docs/blob/8.10/docs/detections/prebuilt-rules/[…]oadable-packages/8-10-1/prebuilt-rules-8-10-1-appendix.asciidoc](https://github.com/elastic/security-docs/blob/8.10/docs/detections/prebuilt-rules/downloadable-packages/8-10-1/prebuilt-rules-8-10-1-appendix.asciidoc) (tries to include non-existent file) and https://github.com/elastic/security-docs/blob/8.10/docs/detections/prebuilt-rules/rule-details/enumerating-domain-trusts-via-nltest-exe.asciidoc (is a target of links but isn't published since it doesn't seem to be in any nav files).

**Comment by terrancedejesus** [comment]
@benironside - As we discussed, the issue is caused by incorrect file names and links to non-existent docs which derive from a security docs generation bug in our existing workflow. Apologies for this.

Here is a bug issue for our repo to have this fixed on our end to avoid this issue in the future: https://github.com/elastic/detection-rules/issues/3032

**Comment by lcawl** [comment]
@elasticmachine run elasticsearch-ci/docs rebuild

**Comment by lcawl** [comment]
@elasticmachine run elasticsearch-ci/docs

**Review by lcawl — APPROVED** [review]
LGTM

**Comment by jrodewig** [comment]
Thanks so much for getting this over the finish line @lcawl. 🏁

**Pull request merged**
