### PR TITLE
Added elasticsearch-js doc examples configuration

### PR DESCRIPTION
**Pull request by delvedor**
As titled, https://github.com/elastic/elasticsearch-js/pull/1011 contains all the doc examples.
Which one should I merge first?

### CODE REVIEW

**Comment by nik9000** [comment]
Looks like that directory doesn't exist in elasticsearch-js.  It doesn't have to have any useful files in it, but it does have to exist for the docs build to be happy.

**Comment by delvedor** [comment]
Thanks! I've merged the newly created docs examples in master :)

**Comment by nik9000** [comment]
@elasticmachine, test this please

**Comment by delvedor** [comment]
@nik9000 the build is now passing, if it's ok for you, we can merge this :)

**Comment by nik9000** [comment]
Lgtm!

**Pull request merged**
