### PR TITLE
Add Azure Marketplace 7.9 docs and make current

### PR DESCRIPTION
**Pull request by russcam**
This commit adds 7.9 branch Azure Marketplace docs, and makes them the current version

### CODE REVIEW

**Comment by russcam** [comment]
This should be merged only when 7.9 is live on the Azure Marketplace. I'll update here when this has happened.

**Comment by gtback** [comment]
I forgot to mention, @russcam: 

> At this point changing current requires a full "rebuild" which we do by logging into the docs build clicking the "Build with Parameters" link, checking the "rebuild" option, and then starting the build. 

- https://github.com/elastic/docs/blob/master/README.asciidoc#adding-new-docs-or-new-branches

Let me know if you need help with this after merging.

**Comment by russcam** [comment]
7.9.0 has gone live on the Marketplace, so merging this in.

**Comment by russcam** [comment]
Thanks @gtback, I've kicked off a rebuild on CI 👍

**Pull request merged**
