### PR TITLE
do not merge - testing Buildkite build job

### PR DESCRIPTION
**Pull request by nkammah**
see context in elastic/docs-projects#136 and elastic/docs-projects#139

### CODE REVIEW

**Comment by gtback** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by nkammah** [comment]
@elasticmachine run elasticsearch-ci/docs
run docs-build

**Comment by nkammah** [comment]
run docs-build

**Comment by nkammah** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by nkammah** [comment]
run docs-build

**Comment by nkammah** [comment]
run docs-build

**Comment by nkammah** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by nkammah** [comment]
run docs-build

**Comment by nkammah** [comment]
@elasticmachine run elasticsearch-ci/docs

**Pull request closed without merging**
