### PR TITLE
Update the current version to 6.2

### PR DESCRIPTION
**Pull request by nrichers**
This PR updates `current` to version 6.2 in preparation for the release tomorrow.

### CODE REVIEW

**Comment by watson** [comment]
@nrichers Good catch with the missing 6.2 branches for the APM project. I just had the same thought and added them here: #308

If it's not too much trouble I'll like to merge #308 in prior to the release to check that the 6.2 branches build without any issues.

**Comment by watson** [comment]
Could we also bump `current` of the following two projects as well as part of this PR?

- [APM Node.js Agent](https://github.com/elastic/docs/pull/307/files#diff-4a701a5adb4359c6abf9b8e1cb38819fR800): Bump to `current: 1.x`
- [APM Python Agent](https://github.com/elastic/docs/pull/307/files#diff-4a701a5adb4359c6abf9b8e1cb38819fR812): Bump to `current: 2.x`

**Comment by watson** [comment]
@nrichers ended up merging #308 and resolving the merge conflict by merging master into this PR. Hope that's ok

**Comment by nrichers** [comment]
@watson Works for me and thanks for doing this!

**Pull request merged**
