### PR TITLE
Don't log confusing lines from parcel

### PR DESCRIPTION
**Pull request by nik9000**
Stops logging `Server running at http://localhost:1234` which is super
confusing because that port number is only in the docker container. It
also suppresses logging of `✨  Built in` until the nginx server is up
and running because it can give folks the false impression that that
docs are ready when it is really just saying the web resources are
ready.

### CODE REVIEW

**Comment by bmorelli25** [comment]
@nik9000 On second thought.. I don't know that this works. When I run an asciidoctor build that fails, there is no output to the console, the script just exits.

**Comment by nik9000** [comment]
> @nik9000 On second thought.. I don't know that this works. When I run an asciidoctor build that fails, there is no output to the console, the script just exits.

I'm not seeing that locally:

```
$ cd apm-server
$ git checkout 7.2
$ ../docs/build_docs --doc ../apm-server/docs/index.asciidoc --chunk 1 --out ../built_docs  --asciidoctor
INFO:docker build:Building the docker image that will build the docs. Expect this to take somewhere between a hundred milliseconds and five minutes.
INFO:build_docs:Building HTML from /doc/apm-server/docs/index.asciidoc
INFO:build_docs:
INFO:build_docs:Error executing: xmllint --nonet --noout --valid /out/built_docs/index.xml
INFO:build_docs:
INFO:build_docs:---
INFO:build_docs:/out/built_docs/index.xml:7939: element listitem: validity error : Element listitem content does not follow the DTD, expecting (calloutlist | glosslist | bibliolist | itemizedlist | orderedlist | segmentedlist | simplelist | variablelist | caution | important | note | tip | warning | literallayout | programlisting | programlistingco | screen | screenco | screenshot | synopsis | cmdsynopsis | funcsynopsis | classsynopsis | fieldsynopsis | constructorsynopsis | destructorsynopsis | methodsynopsis | formalpara | para | simpara | address | blockquote | graphic | graphicco | mediaobject | mediaobjectco | informalequation | informalexample | informalfigure | informaltable | equation | example | figure | table | msgset | procedure | sidebar | qandaset | task | anchor | bridgehead | remark | highlights | abstract | authorblurb | epigraph | indexterm | beginpage)+, got ()
INFO:build_docs:</listitem>
INFO:build_docs:           ^
INFO:build_docs:/out/built_docs/index.xml:8247: element listitem: validity error : Element listitem content does not follow the DTD, expecting (calloutlist | glosslist | bibliolist | itemizedlist | orderedlist | segmentedlist | simplelist | variablelist | caution | important | note | tip | warning | literallayout | programlisting | programlistingco | screen | screenco | screenshot | synopsis | cmdsynopsis | funcsynopsis | classsynopsis | fieldsynopsis | constructorsynopsis | destructorsynopsis | methodsynopsis | formalpara | para | simpara | address | blockquote | graphic | graphicco | mediaobject | mediaobjectco | informalequation | informalexample | informalfigure | informaltable | equation | example | figure | table | msgset | procedure | sidebar | qandaset | task | anchor | bridgehead | remark | highlights | abstract | authorblurb | epigraph | indexterm | beginpage)+, got ()
INFO:build_docs:</listitem>
INFO:build_docs:           ^
```

**Comment by nik9000** [comment]
@bmorelli25, could you have another look at this one? I agree that the log is pretty confusing.

**Comment by bmorelli25** [comment]
@nik9000 I'm still seeing the same thing here. On a failed Asciidoctor build the process just exits without logging any errors.

**Comment by nik9000** [comment]
Try this one, @bmorelli25 !

**Comment by nik9000** [comment]
Thanks for finding the problem @bmorelli25!

**Pull request merged**
