### PR TITLE
Add .NET APM agent 1.8 branch as current

### PR DESCRIPTION
**Pull request by russcam**
This commit updates the configuration for the APM
.NET agent to include the 1.8 branch, and set it as
the current branch.

### CODE REVIEW

**Review by bmorelli25 — CHANGES_REQUESTED** [review]
~`conf.yaml` references the branch in the `apm-agent-dotnet` repo that we build the docs from. As we build from `1.x`, there shouldn't be any updates required to this file on minor releases. Are there docs that you're not seeing live, that you expect to be live?~

**Comment by bmorelli25** [comment]
Alright, @russcam just made my day on zoom–The .NET agent is changing their branching strategy 🎉 . I'll push some changes to this PR tomorrow.

**Comment by bmorelli25** [comment]
b61c0fc Updates documentation links from Stack versioned books (v6.5-v7.x) to point to the 1.8 version of the .NET reference. This is necessary because `1.x` is changing from the current, released version of the documentation to the future, unreleased version. Future minor release will only need to update through the current stack version. For example, if 1.9 released today, the change would only need to be made to `stack/7.x.asciidoc`, `stack/7.12.asciidoc`, and `stack/7.11.asciidoc`.

**Review by bmorelli25 — APPROVED** [review]
😄

**Comment by bmorelli25** [comment]
* [master](https://docs_2066.docs-preview.app.elstc.co/guide/en/apm/agent/dotnet/master/intro.html)
* [1.x](https://docs_2066.docs-preview.app.elstc.co/guide/en/apm/agent/dotnet/1.x/intro.html)
* [1.8 (current)](https://docs_2066.docs-preview.app.elstc.co/guide/en/apm/agent/dotnet/1.8/intro.html)

**Review by gtback — APPROVED** [review]
LGTM!

**Pull request merged**
