### PR TITLE
Add ECK 1.4 branch to conf.yaml

### PR DESCRIPTION
**Pull request by pebrc**
This adds the 1.4 release branch for the upcoming [ECK Operator](https://github.com/elastic/cloud-on-k8s) release.

### CODE REVIEW

**Review by alaudazzi — APPROVED** [review]
LGTM

**Review by gtback — APPROVED** [review]
LGTM!

**Comment by pebrc** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by pebrc** [comment]
@gtback @alaudazzi It seems there is an issue with the docs build self-test, could you merge this PR?

**Comment by pebrc** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by pebrc** [comment]
@elasticmachine run self-test

**Comment by pebrc** [comment]
Looks like we are hitting https://github.com/yarnpkg/yarn/issues/7866

**Pull request merged**
