### PR TITLE
Escape raw versions of replacement characters in README

### PR DESCRIPTION
**Pull request by watson**
Old rendering:

image

New rendering:

image

### CODE REVIEW

**Comment by watson** [comment]
@clintongormley what's the reason this wasn't merged?

**Comment by clintongormley** [comment]
Sorry @watson - the repo was getting so big (1.6GB) that we trimmed all the history.  I asked in techpubs about anything in flight but didn't think to check the open PRs.  My bad.  Would you mind opening again?

**Comment by watson** [comment]
Np 👍 Btw it's still 3GB according to my calculations

**Comment by clintongormley** [comment]
@watson Reclone the repo - then it is lovely and small

**Comment by watson** [comment]
@clintongormley I just did and got down 3GB

**Comment by watson** [comment]
This is the commits I have in master:

```
* 24b43334 (HEAD -> master, origin/master, origin/HEAD, elastic/master) Updated docs
* 5b14f6f2 Updated docs
* 65dd1321 Updated docs
* 64c7d7c2 Updated docs
* 7d5bfcb3 Updated docs
* 2cd8cfb3 Updated docs
* 88453580 Updated docs
* b2550fcb Updated docs
* 608d01f8 Updated docs
* 5fe71590 Updated docs
* 26231c41 Include 6.x .NET API
* 79c1b0f0 Initial commit
```

This is the result of running `du -h -d 1 .`:

```
 80K    ./web
 33M    ./resources
2.8G    ./html
 52K    ./shared
8.0K    ./.github
636K    ./lib
137M    ./.git
4.0K    ./.repos
4.0K    ./.template
4.0K    ./.run
3.0G    .
```

**Comment by clintongormley** [comment]
Ah yes, but the `.git` directory alone was 1.6GB before.  Now it is 137M

**Comment by watson** [comment]
Ah 👍 Got'ya

**Pull request closed without merging**
