### PR TITLE
bumps current version to 8.10

### PR DESCRIPTION
**Pull request by benironside**
This PR changes the "current" version of the documentation to 8.9 and changes that set of docs from "unreleased" to "released".

Do not merge until release day. 

Based on https://github.com/elastic/docs/pull/2722

### CODE REVIEW

**Comment by benironside** [comment]
The following build error is happening:
```10:16:57 INFO:build_docs:  Branch: main, Version: master
10:16:57 INFO:build_docs:Bad cross-document links:
10:16:57 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/cloud-enterprise/3.4/ece-configure-as-remote-clusters.html contains broken links to:
10:16:57 INFO:build_docs:   - en/elasticsearch/reference/8.10/remote-clusters-connect.html#configure-remote-clusters-dynamic
10:16:57 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/cloud-enterprise/3.5/ece-configure-as-remote-clusters.html contains broken links to:
10:16:57 INFO:build_docs:   - en/elasticsearch/reference/8.10/remote-clusters-connect.html#configure-remote-clusters-dynamic
10:16:57 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/cloud-enterprise/3.6/ece-configure-as-remote-clusters.html contains broken links to:
10:16:57 INFO:build_docs:   - en/elasticsearch/reference/8.10/remote-clusters-connect.html#configure-remote-clusters-dynamic
10:16:57 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/cloud-enterprise/current/ece-configure-as-remote-clusters.html contains broken links to:
10:16:57 INFO:build_docs:   - en/elasticsearch/reference/8.10/remote-clusters-connect.html#configure-remote-clusters-dynamic
10:16:57 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/cloud/current/ec-configure-as-remote-clusters.html contains broken links to:
10:16:57 INFO:build_docs:   - en/elasticsearch/reference/8.10/remote-clusters-connect.html#configure-remote-clusters-dynamic
10:16:57 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/cloud/latest/ec-configure-as-remote-clusters.html contains broken links to:
10:16:57 INFO:build_docs:   - en/elasticsearch/reference/8.10/remote-clusters-connect.html#configure-remote-clusters-dynamic
10:17:28 runbld>>> <<<<<<<<<<<< SCRIPT EXECUTION END <<<<<<<<<<<<
```

**Comment by abdonpijpelink** [comment]
The build error should be resolved by https://github.com/elastic/elasticsearch/pull/99401

**Comment by abdonpijpelink** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by jrodewig** [comment]
Rerunning the docs check since I discovered https://github.com/elastic/elasticsearch/pull/99371 broke the build during backports. Should be fixed now, but I want to ensure the release goes smoothly.

@elasticmachine run elasticsearch-ci/docs

**Comment by jrodewig** [comment]
@elasticmachine run elasticsearch-ci/docs

**Pull request merged**
