### PR TITLE
Switch ecs to direct_html

### PR DESCRIPTION
**Pull request by nik9000**
direct_html is faster and more customizable.

### CODE REVIEW

**Comment by nik9000** [comment]
I've made this to get jenkins to generate a commit with the docs built the new way. If it is empty I'd like to merge this. @webmat, I'm trying to migrate all of the docs to this flag because it is *much* faster and much more flexible.

**Comment by nik9000** [comment]
Looks like there are issues with the table rendering I'll have to fix before I can merged this. I'll look now!

**Comment by webmat** [comment]
Under time pressure until mid-next week. Happy to follow up on this at that time :-)

Moar fast builds are always good!

Moar fast

**Comment by nik9000** [comment]
> Under time pressure until mid-next week. Happy to follow up on this at that time :-)

I'm happy to hold this until you are ready for me.

**Comment by nik9000** [comment]
@webmat, how are things looking this week?

**Comment by webmat** [comment]
Unsure whether the release will slip from Wednesday to Thursday. 🤷‍♂

**Comment by nik9000** [comment]
> Unsure whether the release will slip from Wednesday to Thursday. man_shrugging

I believe the change you'd need to make for this is to update how you build the docs to add `--direct_html`. Other than that there is nothing for you to do.

**Comment by nik9000** [comment]
I've merged master into this branch to force it it to recreate the preview. The old preview is still available in the mean time. Both will be [here](http://docs_1559.docs-preview.app.elstc.co/guide/en/ecs/current/index.html)

**Comment by nik9000** [comment]
@webmat, I rebuilt the preview for this one. The diff for it looks pretty much empty once you normalize the HTML, which is what I was hoping for. So this is ready any time you are ready for it.

**Comment by nik9000** [comment]
Thanks @webmat !

**Pull request merged**
