### PR TITLE
Remove unused script ref

### PR DESCRIPTION
**Pull request by brianjolly**
Removes unused script reference which is generating many 404s.

### CODE REVIEW

**Comment by brianjolly** [comment]
https://docs_2289.docs-preview.app.elstc.co/guide/index.html

**Review by gtback — APPROVED** [review]
Looks fine to me. I'm guessing all the search stuff comes through the header now?

I also looked and I'm not sure if the `search.elastic.co` URL above this is doing anything, but we can remove that in a later PR if we want.

**Comment by brianjolly** [comment]
Thanks @gtback, yes, the search all comes through the nav with the Site Search setup. 

I'm happy to drop that `search.elastic.co` script too. It looks like it doesn't even have DNS anymore :)

**Comment by brianjolly** [comment]
Thanks @gtback !

**Pull request merged**
