### PR TITLE
Bumps current version to 8.9

### PR DESCRIPTION
**Pull request by lcawl**
This PR changes the "current" version of the documentation to 8.9 and changes that set of docs from "unreleased" to "released".

**Do not merge until release day**

### CODE REVIEW

**Review by jrodewig — APPROVED** [review]
LGTM

**Comment by lcawl** [comment]
@elasticmachine run elasticsearch-ci/docs rebuild

**Comment by lcawl** [comment]
APM doc link issues being fixed in https://github.com/elastic/apm-server/pull/11279, https://github.com/elastic/apm-server/pull/11278

**Comment by bmorelli25** [comment]
APM redirects merged. Rerunning.

**Comment by bmorelli25** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by lcawl** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by lcawl** [comment]
I created https://github.com/elastic/elasticsearch/pull/97910 to work around the remaining broken links.

**Comment by lcawl** [comment]
@elasticmachine run elasticsearch-ci/docs warnlinkcheck

**Comment by jrodewig** [comment]
@elasticmachine run elasticsearch-ci/docs

**Review by bmorelli25 — APPROVED** [review]
I love it when a plan comes together.

**Pull request merged**
