### PR TITLE
Change current docs branch to 7.15

### PR DESCRIPTION
**Pull request by chriscressman**
DO NOT MERGE UNTIL RELEASE DAY

### CODE REVIEW

**Review by gtback — APPROVED** [review]

**Comment by lcawl** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by chriscressman** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by chriscressman** [comment]
@lcawl Can you take a look at the diff for this PR when you have a moment? I merged master into this branch and resolved conflicts. I'd love for you to confirm that everything looks correct.

**Comment by lcawl** [comment]
The changed files look good to me, but to see the diff I think we need to resolve the current broken links:

> 10:58:23 INFO:build_docs:Bad cross-document links:
10:58:23 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/cloud/current/ec-release-notes-2021-06-15.html contains broken links to:
10:58:23 INFO:build_docs:   - en/kibana/7.15/security-settings-kb.html#ecs-audit-logging-settings
10:58:23 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/cloud/latest/ec-release-notes-2021-06-15.html contains broken links to:
10:58:23 INFO:build_docs:   - en/kibana/7.15/security-settings-kb.html#ecs-audit-logging-settings

... which seem related to https://github.com/elastic/kibana/pull/104685 @gchaps can hopefully tell us what the right replacement URL should be.

**Comment by lcawl** [comment]
@elasticmachine run elasticsearch-ci/docs

**Review by lcawl — APPROVED** [review]
LGTM

**Comment by chriscressman** [comment]
Thanks Lisa! I'll rebuild this periodically to try to catch any issues that come up.

**Comment by chriscressman** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by chriscressman** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by gtback** [comment]
@chriscressman I updated this with the changes from #2205

**Comment by chriscressman** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by chriscressman** [comment]
@elasticmachine run elasticsearch-ci/docs

**Pull request merged**
