### PR TITLE
Add 8.14 branch, bump master to 8.15

### PR DESCRIPTION
**Pull request by bmorelli25**

### CODE REVIEW

**Comment by bmorelli25** [comment]
FAIL: ❌ Enterprise Search Node.js client has no 8.14 branch

**Comment by bmorelli25** [comment]
run docs-build rebuild

**Comment by bmorelli25** [comment]
run docs-build rebuild

**Comment by bmorelli25** [comment]
run docs-build rebuild

**Comment by bmorelli25** [comment]
run docs-build rebuild

**Review by KOTungseth — APPROVED** [review]

**Pull request merged**
