### PR TITLE
[DOCS] Add kibana-extra folder to conf.yaml

### PR DESCRIPTION
**Pull request by lcawl**
Adds the kibana-extra folder to the paths in the conf.yaml

### CODE REVIEW

**Comment by kjbekkelund** [comment]
@lcawl We will only be backporting this to 6.x, so maybe we need to use `exclude_branches` to exclude all earlier versions?

**Comment by lcawl** [comment]
I think that adding exclude_versions would work for most cases in the conf.yaml, but I'm not sure about what to put for the Kibana Reference's index value:

>   ...
> title:      Kibana: Explore, Visualize, and Share
>         sections:
>           -
>             title:      Kibana Reference
>             prefix:     en/kibana
>             current:    6.0
>             branches:   [ master, 6.x, 6.1, 6.0, 5.6, 5.5, 5.4, 5.3, 5.2, 5.1, 5.0, 4.6, 4.5, 4.4, 4.3, 4.2, 4.1, 4.0, 3.0 ]
>             index:      ../kibana-extra/x-pack-kibana/docs/en/index.asciidoc
> ...

 @clintongormley If the path to the index.asciidoc is going to differ between 6.1 and later versions (due to addition of "kibana-extra" folder), do I need to split that content into a new book in the conf.yaml?

**Comment by lcawl** [comment]
It looks like in x-pack-elasticsearch the elasticsearch-extra folder was added all the way back to 0.90: https://github.com/elastic/x-pack-elasticsearch/tree/0.90

**Comment by clintongormley** [comment]
> @clintongormley If the path to the index.asciidoc is going to differ between 6.1 and later versions (due to addition of "kibana-extra" folder), do I need to split that content into a new book in the conf.yaml?

Yes, you can't have different paths to index.asciidoc.  As suggested above, the alternative is to make the same change back to 0.90

**Comment by kjbekkelund** [comment]
@epixa: @lcawl asked me on Slack "Will it be problematic if we add the kibana-extra folder all the way back to 3.0 for docs purposes?" I don't really have an idea about these docs builds, so I'm not sure what effect that has. Do you know what would be okey or not for Kibana?

**Comment by epixa** [comment]
I'm not an expert at our docs system or anything, but I don't think it's going to be a problem to use `kibana-extra` for `x-pack-kibana` all the way back to the 3.0 branch.  6.x introduced the *requirement* to have x-pack-kibana inside a kibana-extra directory, but it was *possible* to use that same setup prior to 6.x as well.  And even if it weren't possible, the docs system doesn't run Kibana or anything like that, it just needs to know where to find the relevant asciidoc files, so it shouldn't be a problem to have the repo cloned to a different place.

**Comment by lcawl** [comment]
Great, thanks, @epixa.

**Comment by kjbekkelund** [comment]
Hm, I wonder if we don't need this change if we revert the change in https://github.com/elastic/x-pack-kibana/pull/4066/files#diff-de10d134c6b3aa58eba72abd79ef45ba (so we don't make any changes to the docs paths at all).

**Comment by kjbekkelund** [comment]
I merged that change, and it seemed to build docs properly. I can create a separate commit to x-pack-kibana that changes the docs path, but as long as docs are working as expected now, it's not something we need to do immediately, I think?

**Pull request merged**
