### PR TITLE
7.4 is current now

### PR DESCRIPTION
**Pull request by nik9000**
Long live 7.4!

### CODE REVIEW

**Comment by nik9000** [comment]
run elasticsearch-ci/docs rebuild

**Comment by nik9000** [comment]
I'm going to let the `elasticsearch-ci/docs` build run because it'll catch any bad links.

**Comment by jrodewig** [comment]
@nik9000  Looks like the CI passed. Gonna go ahead and merge. Thanks again!

**Comment by nik9000** [comment]
> @nik9000 Looks like the CI passed. Gonna go ahead and merge. Thanks again!

Thanks!

**Pull request merged**
