### PR TITLE
Add 6.0 version for apm-server documentation.

### PR DESCRIPTION
**Pull request by simitt**
This should only be merged shortly before rc2 is released.

### CODE REVIEW

**Comment by roncohen** [comment]
I think we can wait until 6.1 is out with versioning them. WDYT @simitt ?

**Comment by simitt** [comment]
In case we need to update something in the documentation we would have the same issues as we had them after releasing alpha1 - either the documentation for the released version or the documentation for the github master branch would be outdated.

**Comment by roncohen** [comment]
I was thinking that it would save us a menu item in the dropdown, but you're right, this is better 👍

**Comment by dedemorton** [comment]
Just a heads-up that these changes require a build --all of the docs. Someone (usually Clint or Deb) does this on the day of the release. You just want to make sure your changes get into the conf.yaml before the full doc build happens.

**Comment by simitt** [comment]
@roncohen should we get this merged in tomorrow then?

**Comment by debadair** [comment]
Yep--I'll check before we kick off the build & merge it if it hasn't been already.

**Pull request merged**
