### PR TITLE
Add ECE 2.11 and ECCTRL 1.5

### PR DESCRIPTION
**Pull request by alpar-t**
Prepare the docs release for the versions to be released.

### CODE REVIEW

**Comment by alpar-t** [comment]
```
14:15:03 INFO:build_docs: - Elastic Cloud Control - The Command-Line: Building master...
14:15:03 INFO:build_docs:Error executing: git archive --format=tar -o /tmp/docsbuild/FQQ6HiOqIU/ecctl/.temp_git_archive.tar 1.5 docs in GIT_DIR /docs_build/.repos/ecctl.git
14:15:03 INFO:build_docs:---out---
14:15:03 INFO:build_docs:
14:15:03 INFO:build_docs:---err---
14:15:03 INFO:build_docs:fatal: Not a valid object name
14:15:03 INFO:build_docs:
14:15:03 INFO:build_docs:---------
14:15:21 runbld>>> <<<<<<<<<<<< SCRIPT EXECUTION END <<<<<<<<<<<<
```
Looks like the Ecctl tag needs to created for this to pass.

**Review by kellyemurphy — APPROVED** [review]
LGTM

**Review by gtback — APPROVED** [review]

**Comment by marclop** [comment]
How do we re-run the docs build for this PR?

**Review by artemnikitin — APPROVED** [review]

**Comment by gtback** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by rhass** [comment]
@elasticmachine update branch

**Comment by rhass** [comment]
@elasticmachine update branch

**Comment by rhass** [comment]
One more time for good luck!

**Comment by rhass** [comment]
closing in favor of #2188

**Comment by gtback** [comment]
> as I couldn't rebase and push into the PR branch.

@rhass do you meant that the `update branch` didn't work or that you couldn't even merge the upstream master branch on the command line? If the former, I can look into what it would take to enable that on this repo. If the latter, then 🤷🏻 .

**Pull request closed without merging**
