### PR TITLE
Updates 7.9 version atts

### PR DESCRIPTION
**Pull request by KOTungseth**
DO NOT MERGE UNTIL RELEASE DAY

This PR updates the shared version attributes for the latest 7.9 documentation release.

### CODE REVIEW

**Comment by KOTungseth** [comment]
@elasticmachine merge upstream

**Review by gtback — APPROVED** [review]

**Comment by KOTungseth** [comment]
@elasticmachine run elasticsearch-ci/docs rebuild

**Comment by KOTungseth** [comment]
@elasticmachine run elasticsearch-ci/docs rebuild

**Comment by gtback** [comment]
@elasticmachine run elasticsearch-ci/docs

**Pull request merged**
