### PR TITLE
Switches X-Pack Reference to Asciidoctor builds

### PR DESCRIPTION
**Pull request by lcawl**
This PR updates the X-Pack Reference (https://www.elastic.co/guide/en/x-pack/index.html) such that it's built via Asciidoctor.

Related to #606

### CODE REVIEW

**Comment by nik9000** [comment]
This one is currently not building with:
```
INFO:build_docs:/tmp/docsbuild/target_repo/html/en/x-pack/6.2/index.xml:445: element partintro: validity error : Element partintro content does not follow the DTD, expecting ((title , subtitle? , titleabbrev?)? , (((calloutlist | glosslist | bibliolist | itemizedlist | orderedlist | segmentedlist | simplelist | variablelist | caution | important | note | tip | warning | literallayout | programlisting | programlistingco | screen | screenco | screenshot | synopsis | cmdsynopsis | funcsynopsis | classsynopsis | fieldsynopsis | constructorsynopsis | destructorsynopsis | methodsynopsis | formalpara | para | simpara | address | blockquote | graphic | graphicco | mediaobject | mediaobjectco | informalequation | informalexample | informalfigure | informaltable | equation | example | figure | table | msgset | procedure | sidebar | qandaset | task | anchor | bridgehead | remark | highlights | abstract | authorblurb | epigraph | indexterm | beginpage)+ , (sect1* | refentry* | simplesect* | section*)) | sect1+ | refentry+ | simplesect+ | section+)), got (titleabbrev )
```

Looks like *some* kind of bug. Not sure what though.

**Comment by lcawl** [comment]
@nik9000 Is that after fixing the issue with the path to the elasticsearch-extra folder per https://github.com/elastic/docs/issues/505#issuecomment-467950707 ? Those are the errors I'm seeing with --lenient

**Comment by nik9000** [comment]
I was getting that error with `--all` rather than the `--doc` version. I've still got fixing `--doc` for this book on my list....

**Comment by lcawl** [comment]
I think it's the same error.  I get a similar partintro error when I build the individual book without --lenient.

**Comment by lcawl** [comment]
The aforementioned error was caused by a <titleabbrev> after all, per https://github.com/elastic/x-pack-elasticsearch/pull/4479

**Comment by lcawl** [comment]
The documentation build errors seem to be solved by #721

**Comment by nik9000** [comment]
This seems to fail to build in the 5.6 branch.

**Comment by nik9000** [comment]
This one is now blocked on #824.

**Comment by nik9000** [comment]
I'm regenerating the diff for this one now.

**Comment by nik9000** [comment]
The differences seem to amount to:
1. Some different ids (bad but not a big deal in legacy docs)
2. A few ordered lists being reset when they shouldn't be (bad but not a huge deal in legacy docs)
3. A few ordered lists not being reset when they shouldn't be being reset but they were (good)
4. Table headings moving from the tbody into thead (good)
5. Lines with missing variables appearing when they were previously gone (good)
6. Some indentation changes around admonishments inside of callouts. (meh)

At this point switching to Asciidoctor is a net positive on the results so I think we should merge this. I don't think any of the problems are worth going back and fixing at this point. But that is just my opinion.

**Comment by nik9000** [comment]
@lcawl, I'm going to leave the merging this to you. If you agree with my reasoning then merge when ready1

**Pull request merged**
