### PR TITLE
Add 7.15 docs branch

### PR DESCRIPTION
**Pull request by chriscressman**
We can merge this after all repos publish a 7.15 branch, and CI jobs succeed.

### CODE REVIEW

**Review by gtback — APPROVED** [review]

**Comment by chriscressman** [comment]
@elasticmachine run elasticsearch-ci/docs rebuild

**Comment by chriscressman** [comment]
@karenzone Feel free to merge if you get a passing build

**Comment by karenzone** [comment]
@elasticmachine run elasticsearch-ci/docs rebuild

**Comment by karenzone** [comment]
@elasticmachine run elasticsearch-ci/docs rebuild

**Comment by karenzone** [comment]
@elasticmachine run elasticsearch-ci/docs rebuild

**Comment by chriscressman** [comment]
Thanks for completing this @karenzone !

**Pull request merged**
