### PR TITLE
Add ECK 2.1 branch.

### PR DESCRIPTION
**Pull request by naemono**
Adds the branch for the ECK 2.1 release.

### CODE REVIEW

**Review by gtback — APPROVED** [review]
LGTM!

The error is:
```
12:35:47 INFO:build_docs:asciidoctor: WARNING: invalid reference: release-notes-2.1.0
```

**Comment by naemono** [comment]
maybe because this isn't merged as of yet @gtback ?  https://github.com/elastic/cloud-on-k8s/pull/5427. I suspect that's probably the issue.  I'll have this re-run when that is merged.

**Comment by gtback** [comment]
@naemono yep, that's exactly it. You can make a comment like 
`@/elasticmachine run elasticsearch-ci/docs` it will rerun the docs build without needing to push another commit.

(I put the slash in there so it doesn't run now; take it out before you actually run it)

**Comment by naemono** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by naemono** [comment]
@elasticmachine run elasticsearch-ci/docs

the missing bit was https://github.com/elastic/cloud-on-k8s/pull/5444, which backported the release notes to 2.1 branch and wasn't merged.

**Pull request merged**
