### PR TITLE
apm: Neutral naming for apm-agent-nodejs

### PR DESCRIPTION
**Pull request by v1v**
### What

Neutral naming of git branches for the elastic/apm-agent-nodejs

### Issues

**Requires** https://github.com/elastic/apm-agent-nodejs/pull/2535

### CODE REVIEW

**Review by bmorelli25 — APPROVED** [review]

**Review by trentm — APPROVED** [review]

**Comment by v1v** [comment]
run elasticsearch-ci/docs

**Comment by v1v** [comment]
elastic/apm-agent-nodejs#2535 has been merged and I triggered a new build, so if it gets green then I'll merge this PR

**Comment by v1v** [comment]
run elasticsearch-ci/docs

**Comment by v1v** [comment]
I just merged elastic/apm-agent-nodejs#2535 and triggered a new build for this PR, so if it goes green then I'll merge this PR

**Pull request merged**
