### PR TITLE
Integrate feedback mechanism

### PR DESCRIPTION
**Pull request by nik9000**
Integrate a fancy feedback mechanism.

### CODE REVIEW

**Comment by nik9000** [comment]
@elasticmachine run elasticsearch-ci/docs rebuild

**Comment by nik9000** [comment]
Here i the feedback mechanism to have a look at: http://docs_1383.docs-preview.app.elstc.co/guide/en/cloud/current/ec-getting-started-trial.html

**Comment by alaudazzi** [comment]
@nik9000 @Adrian-J We got the green light form Shay to proceed. The mechanism is OK, we just need to adjust the layout (replace thumbs up/down with something else).

**Comment by nik9000** [comment]
@Adrian-J and @alaudazzi check out http://docs_1383.docs-preview.app.elstc.co/guide/en/cloud/current/index.html . I've done quite a bit of messing around with qualtrix and it looks OK now. It isn't perfect at all, but it is something.

**Comment by alaudazzi** [comment]
@nik9000 Thank you! 
- Less space between the "Yes/No" buttons
- Use an indicator that the button was clicked (blue colour?)
Other than that, that's just great!

**Comment by markdecado** [comment]
@nik9000 - thanks for this, great progress.

Can we remove 'Powered by Qualtrics', people may object to this. We should change the Thank You message also. I'll look into the customization of this.

**Comment by nik9000** [comment]
> * Less space between the "Yes/No" buttons
> 
> * Use an indicator that the button was clicked (blue colour?)
>   Other than that, that's just great!

Done.

**Comment by nik9000** [comment]
> Can we remove 'Powered by Qualtrics', people may object to this.

Sure. I'll do it now. Qualtrix doesn't seem to like that but they don't seem to ban it.

> We should change the Thank You message also. I'll look into the customization of this.

You can customize it, yeah. If you have text I can do it because I think I remember where it is.

**Pull request merged**
