### PR TITLE
Add ECK 2.0 branch

### PR DESCRIPTION
**Pull request by pebrc**
Adds the branch for the ECK 2.0 release.

### CODE REVIEW

**Review by gtback — APPROVED** [review]
LGTM whenever you're ready to merge. 

It looks like the current error is:

```
03:33:41 INFO:build_docs:asciidoctor: WARNING: invalid reference: release-notes-2.0.0
```

**Comment by pebrc** [comment]
@elasticmachine run docs build

I merged the release notes only after opening this PR

**Comment by pebrc** [comment]
@elasticmachine, run elasticsearch-ci/docs

I merged the release notes only after opening this PR

**Comment by gtback** [comment]
Looks great! Feel free to merge when appropriate.

**Pull request merged**
