### PR TITLE
Switch link attributes to relative paths

### LINKED ISSUE #1029: Move to root-relative URLs for links between books
Most of the Elastic documentation now uses attributes to fill in the URL for links between books. For example, in https://github.com/elastic/stack-docs/blob/7.3/docs/en/install-upgrade/installing-stack.asciidoc:

> Install the Elastic Stack products you want to use in the following order:
> . Elasticsearch ({ref}/install-elasticsearch.html[install instructions])
> . Kibana ({kibana-ref}/install.html[install])
> . Logstash ({logstash-ref}/installing-logstash.html[install])
> . Beats ({beats-ref}/getting-started.html[install instructions])
> . APM Server ({apm-server-ref-70}/installing.html[install instructions])
> . Elasticsearch Hadoop ({hadoop-ref}/install.html[install instructions])

These attributes ( {ref}, {kibana-ref}, etc) are defined in https://github.com/elastic/docs/blob/master/shared/attributes.asciidoc

We should consider changing the values in those attributes such that they're root-relative instead of specifying the full URL. This would make the links work better in scenarios where we're providing a full set of offline documentation.

It would mean you wouldn't be able to check your links if you're building a single book, however. Since we do link checks when we build *all* documentation, however, and that's the build we're running in our PR checks now, I think that is okay.

### PR DESCRIPTION
**Pull request by nik9000**
This should make it less likely for us to accidentally "escape" from the
preview site.

Closes #1029

### CODE REVIEW

**Comment by nik9000** [comment]
Run elasticsearch-ci/docs rebuild

Let's see if this changes anything.

**Comment by nik9000** [comment]
That didn't make the links! I've pushed an update and will rerun a rebuild on it once the current docs build finishes.

**Comment by nik9000** [comment]
retests this please

**Comment by nik9000** [comment]
retest this please

**Comment by nik9000** [comment]
@elasticmachine elasticsearch-ci/docs rebuild please

**Comment by lcawl** [comment]
Either I'm not understanding the point of this change or it's not working yet.  
When I click on the links in http://docs_1233.docs-preview.app.elstc.co/guide/en/elastic-stack-overview/master/ml-api-quickref.html for example, I would have expected to stay on the preview site, but that's not happening

**Comment by nik9000** [comment]
@elasticmachine elasticsearch-ci/docs rebuild

**Comment by nik9000** [comment]
@elasticmachine run elasticsearch-ci/docs rebuild

**Comment by nik9000** [comment]
Sigh. I should have watched more closely. I forgot `run` so now my preview doesn't have the right results and it'll take two hours to generate. Well, hopefully it'll be there in the morning!

**Comment by nik9000** [comment]
The preview that I do have looks pretty good though!

**Comment by nik9000** [comment]
> it's not working yet.

It wasn't. I hadn't forced a full rebuild properly yet.

I really need to fix detecting changes on those files....

**Comment by nik9000** [comment]
OK! This doesn't work!

**Comment by nik9000** [comment]
It ends up with a lot of output that looks like:
```
<a class="ulink" href="link:/guide/en/apm/server/6.4/transactions.html#transaction-spans"
```

Without it we just output the text.

I think we rely all over the place on `https://` triggering a link. I'll have to think harder about this.

**Comment by nik9000** [comment]
This isn't going to work as is so I'm going to close it and make something else.

**Pull request closed without merging**
