### PR TITLE
Improving Visual Content Hierarchy and Legibility

### PR DESCRIPTION
**Pull request by jonasll**
# Improving Visual Hierarchy and Legibility

This PR aims at improving the consumability across all guides. Impact of these changes have been reviewed across the `elasticsearch`, `kibana`, `beats` and `workplace-search` books. 

Here's a list of the main tweaks (before and after included):

## 1. Header and Paragraph Hierarchy
This change aimed and creating better distinctions between sections and group information together with their headers. The previous iteration made the documents feel crowded and difficult to parse when jumping from section to section.

hierarchy

---

## 2. Table Legibility
The current styles are very tight, and information is hard to consume for tables, large and small.

tables

---

## 3. Miscellaneous Alignment and Padding Tweaks / Bug Fixes
Devil is in the detail, and some of the misaligned or inconsistent objects have been fine-tuned. Here are a few examples:

spacing

align

crumbs

---

## Bonus: Improved Step Process for Image-Intensive Guides (i.e. Solutions Guides)
Solutions Guides tend to be more visually rich, especially around flows and sequences. While not entirely related to this PR, it highlights some of the tweaks around Figure Caption hierarchy, and overall displays the combination of many of the aforementioned tweaks into a single view. The final product is strikingly more consumable.

ws_service

---

@dedemorton @debadair for review. Please add anyone else who you may think can add value to this review.

### CODE REVIEW

**Comment by dedemorton** [comment]
This is great. I will test the new styles against a few books, but in the mean time, wanted to point out that we have a few issues open related to CSS and layout. Adding links here so we remember to check for these problems and close them.

https://github.com/elastic/docs/issues/229
https://github.com/elastic/docs/issues/126
https://github.com/elastic/docs/issues/265

**Comment by jonasll** [comment]
Thanks for highlighting this @dedemorton. Upon review, many of these previously raised items (https://github.com/elastic/docs/issues/229) are being addressed by the general hierarchy tuning. It seems like 265 is outside the scope of these fixes and require a more thorough look into the build pipeline.

I would love to merge this before the end of the week as it will help us continue to drive the docs transition from Swiftype.com to Elastic.co smoothly. Thanks!

**Comment by dedemorton** [comment]
I've looked through the changes that you're proposing. Overall the design _is_ a lot easier to read, but I think the css needs some more tweaking. I wonder if you've been in touch with @Adrian-J about the site redesign? Maybe you can leverage some of the design work he's already done to make the layout work even better? I think what you've done is an improvement in terms of readability, but IMO we should make sure it's in line with Elastic design goals. 

Here are a few issues that I noticed. I'll include a link to the live page for your convenience.

**Need more space after non-screenshot images**
https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-overview.html

image

**Space between screen capture and tip is too big**
https://www.elastic.co/guide/en/beats/filebeat/current/view-kibana-dashboards.html

image

**Extra padding causes too much wrapping in table cols**
https://www.elastic.co/guide/en/beats/filebeat/current/directory-layout.html

image

**Too much space after sections makes it look like the page ends**
https://www.elastic.co/guide/en/beats/filebeat/current/configuration-filebeat-options.html

image

**Comment by jonasll** [comment]
Thanks @dedemorton, I appreciate the comments. My goal here is not to make it perfect, but to iteratively improve. I'll see how I can quickly improve based on some of the items above, but unless something is broken, I would like to push this out. A little bit of inconsistency is better in the short in my opinion than the state we've been in for the last year. I'll push one more commit with tweaks, will ping you, and we'll go from there.

**Comment by dedemorton** [comment]
Yup, I totally get that! This was my list of stuff that looks worse now than it did before, not an attempt to make things perfect. :-) If you want perfect, hold my beer....

**Comment by jonasll** [comment]
I've addressed the items as per the feedback, see below:

## 1. Reduced Table Padding
Unfortunately, I can only optimize for when the page is at full-width, the in-between breakpoints are bound to break all tables: yesterday, today and tomorrow. A sad reality of the web.

Screen Shot 2020-03-05 at 4 52 06 PM


## 2. Screenshot and Infoblock Spacing Adjusted
Some conditions caused the margins to compound. This was reviewed.
Screen Shot 2020-03-05 at 5 00 06 PM
Screen Shot 2020-03-05 at 4 52 20 PM


I did not address the extended spacing at the bottom of the page, as it is an edge case that requires a few things to come together. There likely isn't a good solution for this in the short term unless we refactor the markup itself (which is out of scope now and tomorrow, given the current Docs Initiative led by Jason Z and team).

@dedemorton Please let me know if this addresses your top-of-mind items.

**Comment by dedemorton** [comment]
Agreed...we shouldn't put too much work into this right now.

I guess you can apply the change and see if people complain? We can always fine tune the styles more later I suppose.

**Comment by jonasll** [comment]
I strongly believe that this is a considerable improvement, and I agree that should anything arise, I will own the tweaking to ensure nothing is in a broken state. +1 on iterations, but I will let that for someone else who can own this long-term. Thanks for your help @dedemorton

**Comment by jonasll** [comment]
PS. This will be merged at 8am PST on March 6th (tomorrow).

**Comment by jonasll** [comment]
@debadair requested to hold on the merge for a few hours.

**Pull request merged**
