### PR TITLE
Make ECS 1.7 the current release

### PR DESCRIPTION
**Pull request by webmat**
Do not merge. Please let the ECS team merge this at the appropriate time.

### CODE REVIEW

**Comment by webmat** [comment]
Seems like this is related to https://github.com/elastic/cloud/pull/70205

**Comment by webmat** [comment]
@elasticmachine, run elasticsearch-ci/docs

**Review by gtback — APPROVED** [review]
Approved! I'll mark it as Draft so no one (especially me 😉 ) accidentally merges it, but feel free to merge when ready.

**Comment by bmorelli25** [comment]
What's the reasoning behind setting `1.7` as current, but only setting `:ecs_version:            1.7` in `master` and not also `7.10`? I don't think this creates a good experience for our users. Any links from stack current (`7.10`) to ECS documentation will be met with a yellow header:

> "A newer version is available. For the latest information, see the current release documentation."

**Comment by webmat** [comment]
@bmorelli25 ECS 1.7 is to be adopted by Elastic Stack 7.11. That's why we release ECS 1 week *after* the previous stack release :-)

**Pull request merged**
