### PR TITLE
Add ECS Logging Java Reference to doc build

### PR DESCRIPTION
**Pull request by bmorelli25**
## Summary

This PR adds the [ECS Logging Java Reference](https://github.com/elastic/ecs-logging-java) to the elastic.co documentation build.

## Related

* For https://github.com/elastic/ecs-logging-java/pull/112

### CODE REVIEW

**Comment by felixbarny** [comment]
What's the best course of action to sync this PR with elastic/ecs-logging-java#112?

While I think a small gap between merging elastic/ecs-logging-java#112 and the docs being available is totally fine, I wouldn't want several days in that somewhat inconsistent state.

Could you merge elastic/ecs-logging-java#112 yourself and then merge this one after the test succeed (which probably depend on elastic/ecs-logging-java#112 to be merged?).

After that's done, I'd like to add a `0.x` branch and configure that as the current one for the docs. Once 1.0 is released (scheduled for the 7.11 timeframe), we can add a `1.x` branch and configure that to be the active one. I can do the PRs for that and it would be nice if you could review and merge them.

**Comment by bmorelli25** [comment]
@elasticmachine, run elasticsearch-ci/docs rebuild

**Review by gtback — APPROVED** [review]
LGTM!

**Comment by bmorelli25** [comment]
There are some cross-doc links that need to be fixed. I'll open a PR in `ecs-logging-java` to clean these up.

```
09:52:52 INFO:build_docs:Bad cross-document links:
09:52:52 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/ecs-logging/java/current/_structured_logging_with_log4j2.html:
09:52:52 INFO:build_docs:   - en/elasticsearch/reference/7.10/current/object.html
09:52:52 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/ecs-logging/java/current/intro.html:
09:52:52 INFO:build_docs:   - en/beats/filebeat/7.10/master/ilm.html
09:52:52 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/ecs-logging/java/current/setup.html:
09:52:52 INFO:build_docs:   - en/apm/agent/java/current/current/config-logging.html
09:52:52 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/ecs-logging/java/master/_structured_logging_with_log4j2.html:
09:52:52 INFO:build_docs:   - en/elasticsearch/reference/7.10/current/object.html
09:52:52 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/ecs-logging/java/master/intro.html:
09:52:52 INFO:build_docs:   - en/beats/filebeat/7.10/master/ilm.html
09:52:52 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/ecs-logging/java/master/setup.html:
09:52:52 INFO:build_docs:   - en/apm/agent/java/current/current/config-logging.html
```

**Comment by bmorelli25** [comment]
@elasticmachine, run elasticsearch-ci/docs rebuild

**Pull request merged**
