### PR TITLE
Update folders for es plugin descriptor and versions.properties for elasticsearch master

### PR DESCRIPTION
**Pull request by breskeby**
With merging https://github.com/elastic/elasticsearch/pull/72861 we've moved the version.properties and plugin descriptor file within the elasticsearch repo (on master for now, 7.x will follow). 
This PR updates the reference folders to reflect this change.

### CODE REVIEW

**Review by gtback — APPROVED** [review]
LGTM!

**Comment by gtback** [comment]
@breskeby It looks like this is failing because it's looking for a file `buildSrc/version.properties`. 

```
07:53:29 INFO:build_docs:asciidoctor: ERROR: dependencies-versions.asciidoc: line 6: include file not found: /tmp/docsbuild/PA3gkoUIUz/elasticsearch/buildSrc/version.properties
```

Is it possible that some files from `buildSrc/` are still needed on the master branch? The docs build does a sparse checkout and only the listed files/directories are available during the build.

**Comment by breskeby** [comment]
@gtback can we rerun the docs build. this should be fixed now

**Comment by breskeby** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by breskeby** [comment]
hmm. this is still failing with 

```17:03:37 INFO:build_docs:Error executing: git archive --format=tar -o /tmp/docsbuild/IRLJKpD2iK/elasticsearch/.temp_git_archive.tar 6.5 build-tools-internal in GIT_DIR /docs_build/.repos/elasticsearch.git```
but I don't understand what's actually going wrong here 🤔

**Comment by gtback** [comment]
Yep, I was just looking at this:

```
10:03:37 INFO:build_docs:Error executing: git archive --format=tar -o /tmp/docsbuild/IRLJKpD2iK/elasticsearch/.temp_git_archive.tar 6.5 build-tools-internal in GIT_DIR /docs_build/.repos/elasticsearch.git
10:03:37 INFO:build_docs:---out---
10:03:37 INFO:build_docs:
10:03:37 INFO:build_docs:---err---
10:03:37 INFO:build_docs:fatal: pathspec 'build-tools-internal' did not match any files
```

It's saying that `build-tools-internal doesn't exist on the 6.5 branch. Indeed, it looks like 6.3, 6.4, and 6.5 are left out of that `exclude_branches` list (and probably should have been excluded on whichever list you copied that from).

**Review by gtback — APPROVED** [review]

**Pull request merged**
