### PR TITLE
Asciidoctor: Enable some more rubocop rules

### PR DESCRIPTION
**Pull request by nik9000**
Removes some rubocop suppressions and fixes the warnings that they find
without changnig any behavior.

### CODE REVIEW

**Comment by jarpy** [comment]
Happy am I, in particular, one of these changes to see.

**Comment by nik9000** [comment]
Nik's local jenkins install, run self-test please. Thank you.

**Comment by nik9000** [comment]
> Nik's local jenkins install, run self-test please. Thank you.

Wonderful.

**Comment by nik9000** [comment]
Oh neat! My local jenkins is pushing that self-test in the checks above. That is unexpected....

**Pull request merged**
