### PR TITLE
Drop support for asciidoctor outside of docker

### PR DESCRIPTION
**Pull request by nik9000**
We initially supported asciidoctor in the same way that the docs build
supported everything else: by copying the source into the repo. Now that
we have docker to resolve our dependencies we don't need to do that. This
blasts asciidoctor from the repo and the infrastructure for copying it
locally.

### CODE REVIEW

**Comment by jarpy** [comment]
This diff is so red, GitHub can't show even show it.

**Comment by nik9000** [comment]
@elasticmachine, run self-test

**Comment by nik9000** [comment]
Self test failed here! Interesting!

**Comment by nik9000** [comment]
The self-test doesn't fail locally. I'm going to kick off an intake build and have a look at that too.

**Comment by nik9000** [comment]
The self-test failure is caused by different path iteration order and I have proposed a fix in #615.

**Pull request merged**
