### PR TITLE
Escape raw versions of replacement characters in README

### PR DESCRIPTION
**Pull request by watson**
Reopen of #276

### CODE REVIEW

**Comment by clintongormley** [comment]
@watson Actually this doesn't work as expected. Github uses Asciidoctor to render asciidoc, but we use Asciidoc, which ends up producing this:

image

I hoped that using `+`  instead of ` might work for both, but asciidoc ends up replacing the characters.

The following works for asciidoc and (hopefully) asciidoctor too:

```
[horizontal]
`--`::      -- (em dash)
+&#x2e;..+::    ...
+&#x2d;>+::     ->
+<&#x2d;+::     <-
+&#x3d;>+::     =>
+<&#x3d;+::     <=
+&#x28;C)+::    (C)
+&#x28;TM)+::   (TM)
+&#x28;R)+::    (R)
```

**Comment by watson** [comment]
Is the README rendered and displayed in other locations than on GitHub?

**Comment by clintongormley** [comment]
> Is the README rendered and displayed in other locations than on GitHub?

It is intended to be built locally with the build_docs tool - it just so happens that it also renders on github.  other than that, no

**Comment by watson** [comment]
Updated.

I had to change `+` for `` ` `` though. Not sure what the `+` was for?

**Comment by clintongormley** [comment]
Nope, in asciidoc this now renders as 

image

`+` and ```  are different forms of passthrough in asciidoc.  This is yet another place that asciidoctor has diverged from asciidoc.  Given that the primary purpose of this document is to be rendered with asciidoc (and that display on github is secondary), I think we shouldn't merge this PR.

**Comment by watson** [comment]
I disagree. If there's no way to mark this up so it renders correctly on both GitHub and if you clone the repo and build it locally, IMHO I think we should optimize for reading the README on GitHub as this is the place most people will read it. I imagine only people who work with docs everyday will view it locally, and this documentation is targeted people who are new to working with asciidocs and hence will view it on GitHub.

**Comment by clintongormley** [comment]
You know what we can do?  Just drop the monospacing.  So remove the `` ` ``, the `+`, and the html encoding, and just use the `\` escaping as per your original PR.  That SHOULD render properly for both.

**Comment by watson** [comment]
Updated using conditional branching and validated both locally and on github. It looks ok on both using this technique. Is that ok?

**Comment by clintongormley** [comment]
thanks @watson

**Pull request merged**
