### PR TITLE
Change current branch to 7.13

### PR DESCRIPTION
**Pull request by chriscressman**
DO NOT MERGE UNTIL RELEASE DAY

### CODE REVIEW

**Comment by chriscressman** [comment]
@elasticmachine run elasticsearch-ci/docs rebuild

**Review by jrodewig — APPROVED** [review]
👍

**Review by gtback — APPROVED** [review]

**Comment by lockewritesdocs** [comment]
@elasticmachine update branch

**Comment by chriscressman** [comment]
@elasticmachine run elasticsearch-ci/docs rebuild

**Comment by lockewritesdocs** [comment]
@elasticmachine run elasticsearch-ci/docs rebuild

**Comment by chriscressman** [comment]
@elasticmachine run elasticsearch-ci/docs rebuild

**Pull request merged**
