### PR TITLE
Bump current version to 7.16

### PR DESCRIPTION
**Pull request by debadair**
DO NOT MERGE UNTIL RELEASE DAY

### CODE REVIEW

**Comment by bmorelli25** [comment]
Pushed a fix for the 1000+ broken APM links in 6ff14c4.

**Comment by bmorelli25** [comment]
@elasticmachine, run elasticsearch-ci/docs

Updating to see if my PRs ⬆️ ⬆️ ⬆️ worked.

**Comment by karenzone** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by debadair** [comment]
There are some cloud links that are still wonky, but going to go ahead and merge & build without the link check to get the release rolling.

**Review by nastasha-solomon — APPROVED** [review]

**Comment by gtback** [comment]
Admin-merging this per @debadair 's [comment](https://github.com/elastic/docs/pull/2299#issuecomment-988034738).

**Pull request merged**
