### PR TITLE
Update conf.yaml for Cloud Enterprise to pull from 1.0.0-alpha3 branch

### PR DESCRIPTION
**Pull request by nrichers**
Changed lines 393-395, and tested with `build_docs.pl --all`

```
            current:    1.0.0-alpha3
            branches:
                - 1.0.0-alpha3
```

### CODE REVIEW

**Comment by nrichers** [comment]
@uric Your LGTM for the conf.yaml changes, please.

**Comment by clintongormley** [comment]
LGTM - not sure why the diff is showing all the other alpha4 -> alpha5 changes, looks fine locally

**Comment by nrichers** [comment]
@clintongormley. I had done a pull and a rebase before making changes. I take it `alpha5` is the correct alpha version that needs to be in conf.yaml or should I squash this commit and start over?

**Comment by nrichers** [comment]
@clintongormley Not sure why those show up, either. I had pulled the files and rebased before making changes.

**Pull request merged**
