### PR TITLE
Add ecs-log-zerolog

### PR DESCRIPTION
**Pull request by bmorelli25**
Content in https://github.com/elastic/ecs-logging-go-zerolog/pull/10

### CODE REVIEW

**Comment by bmorelli25** [comment]
@elasticmachine, run elasticsearch-ci/docs

**Comment by colleenmcginnis** [comment]
Hmmm this new book is showing up in the [Jenkins preview](https://docs_2916.docs-preview.app.elstc.co/guide/en/ecs-logging/index.html), but not in the [Buildkite preview](https://docs_bk_2916.docs-preview.app.elstc.co/guide/en/ecs-logging/index.html). @bmorelli25 is that expected?

**Comment by bmorelli25** [comment]
> Hmmm this new book is showing up in the [Jenkins preview](https://docs_2916.docs-preview.app.elstc.co/guide/en/ecs-logging/index.html), but not in the [Buildkite preview](https://docs_bk_2916.docs-preview.app.elstc.co/guide/en/ecs-logging/index.html). @bmorelli25 is that expected?

Yes. I forgot to rerun the BK build after https://github.com/elastic/ecs-logging-go-zerolog/pull/10 was merged :) Doing that now.

**Comment by bmorelli25** [comment]
Boom: https://docs_bk_2916.docs-preview.app.elstc.co/guide/en/ecs-logging/index.html

**Comment by colleenmcginnis** [comment]
Oh gosh. @bmorelli25 I hate to do this to you _after_ you _just_ rebuilt the preview, but we should probably add this to the dropdown too. 😬 

Screenshot 2024-02-02 at 12 45 55 PM

**Comment by bmorelli25** [comment]
Great catch! On it 🦖

**Pull request merged**
