### PR TITLE
Updated configuration for js client

### PR DESCRIPTION
**Pull request by delvedor**
Hello!
As you may know, I'm working on the [new JavaScript client](https://github.com/elastic/elasticsearch-js/tree/next) for Elasticsearch, the code is ready as well as the documentation, the plan is to release the new client with a blog post (https://github.com/elastic/blog/issues/580) at the same time of ES-rc1 *(or slightly later)*.

The current client will be migrated to a new repo to keep all the history, which will be `elasticsearch-js-legacy` *(I still have to create it)*.

With this pr I'm updating the documentation for the new client, but I don't know if we want to keep the old documentation as well for a while.

I'll keep the pr in *draft* mode until the new client is ready to go.

/cc @elastic/es-clients @spalger

### CODE REVIEW

**Comment by nik9000** [comment]
I talked with @delvedor about this this morning - we'll merge the old docs into the new repo in a branch called `legacy` and tag it `15.x`. We'll use that to keep building the 15.x docs. I'll then [implement](#753) support for explicitly configuring the `15.x` branch as coming from the `legacy` branch in the js repo and make sure the branch is rendered as "old". Then we can remove the funny `15.x` tag.

**Comment by nik9000** [comment]
Note that we might have pages that don't exist in the new version of the docs. I propose at least initially we are ok with that. Once we have tighter control of the redirects on the public web site we can fix the problem quickly.

**Comment by nik9000** [comment]
There are two things blocking this:
1. Merge master and update the repo in the list from `elasticsearch-js-legacy` to `elasticsearch-js`. Simple enough.
2. It looks like the legacy javascript docs aren't compatible with asciidoctor. I'm going to try and fix that before we merge this.

**Comment by nik9000** [comment]
> It looks like the legacy javascript docs aren't compatible with asciidoctor. I'm going to try and fix that before we merge this.

Because the new docs aren't compatible with AsciiDoc! Which is fine. We're migrating to Asciidoctor.

**Comment by delvedor** [comment]
> It looks like the legacy javascript docs aren't compatible with asciidoctor. I'm going to try and fix that before we merge this.

Fixed in https://github.com/elastic/elasticsearch-js/pull/793 🎉

**Comment by nik9000** [comment]
@delvedor, I pushed some updates. The docs build now but the link check fails. You can test it locally with:

```
./build_docs --all --target_repo git@github.com:elastic/built-docs.git --open
```

That will take a *long* time because it has to download a bunch of stuff. Try and do it in a place with a nice internet connection..... Here are the failures I see locally though:
```
INFO:build_docs:Bad cross-document links:
INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/elastic-stack-overview/6.3/http-clients.html:
INFO:build_docs:   - en/elasticsearch/client/javascript-api/current/auth-reference.html
INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/elastic-stack-overview/6.4/http-clients.html:
INFO:build_docs:   - en/elasticsearch/client/javascript-api/current/auth-reference.html
INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/elastic-stack-overview/6.5/http-clients.html:
INFO:build_docs:   - en/elasticsearch/client/javascript-api/current/auth-reference.html
INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/elastic-stack-overview/6.6/http-clients.html:
INFO:build_docs:   - en/elasticsearch/client/javascript-api/current/auth-reference.html
INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/elastic-stack-overview/6.7/http-clients.html:
INFO:build_docs:   - en/elasticsearch/client/javascript-api/current/auth-reference.html
INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/elastic-stack-overview/7.0/http-clients.html:
INFO:build_docs:   - en/elasticsearch/client/javascript-api/current/auth-reference.html
INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/elastic-stack-overview/7.x/http-clients.html:
INFO:build_docs:   - en/elasticsearch/client/javascript-api/current/auth-reference.html
INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/elastic-stack-overview/current/http-clients.html:
INFO:build_docs:   - en/elasticsearch/client/javascript-api/current/auth-reference.html
INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/elastic-stack-overview/master/http-clients.html:
INFO:build_docs:   - en/elasticsearch/client/javascript-api/current/auth-reference.html
INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/elasticsearch/client/javascript-api/15.x/changelog.html:
INFO:build_docs:   - en/elasticsearch/client/javascript-api/current/configuration.html
INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/elasticsearch/client/javascript-api/5.x/_api_reference.html:
INFO:build_docs:   - en/elasticsearch/plugins/5.x/ingest.html
INFO:build_docs:   - en/elasticsearch/reference/5.x/cat-alias.html
INFO:build_docs:   - en/elasticsearch/reference/5.x/cat-allocation.html
INFO:build_docs:   - en/elasticsearch/reference/5.x/cat-count.html
INFO:build_docs:   - en/elasticsearch/reference/5.x/cat-fielddata.html
INFO:build_docs:   - en/elasticsearch/reference/5.x/cat-health.html
INFO:build_docs:   - en/elasticsearch/reference/5.x/cat-indices.html
INFO:build_docs:   - en/elasticsearch/reference/5.x/cat-master.html
INFO:build_docs:   - en/elasticsearch/reference/5.x/cat-nodeattrs.html
INFO:build_docs:   - en/elasticsearch/reference/5.x/cat-nodes.html
INFO:build_docs:   - en/elasticsearch/reference/5.x/cat-pending-tasks.html
INFO:build_docs:   - en/elasticsearch/reference/5.x/cat-plugins.html
INFO:build_docs:   - en/elasticsearch/reference/5.x/cat-recovery.html
INFO:build_docs:   - en/elasticsearch/reference/5.x/cat-repositories.html
INFO:build_docs:   - en/elasticsearch/reference/5.x/cat-segments.html
INFO:build_docs:   - en/elasticsearch/reference/5.x/cat-shards.html
INFO:build_docs:   - en/elasticsearch/reference/5.x/cat-snapshots.html
INFO:build_docs:   - en/elasticsearch/reference/5.x/cat-templates.html
INFO:build_docs:   - en/elasticsearch/reference/5.x/cat-thread-pool.html
INFO:build_docs:   - en/elasticsearch/reference/5.x/cat.html
INFO:build_docs:   - en/elasticsearch/reference/5.x/cluster-allocation-explain.html
INFO:build_docs:   - en/elasticsearch/reference/5.x/cluster-health.html
INFO:build_docs:   - en/elasticsearch/reference/5.x/cluster-nodes-hot-threads.html
INFO:build_docs:   - en/elasticsearch/reference/5.x/cluster-nodes-info.html
INFO:build_docs:   - en/elasticsearch/reference/5.x/cluster-nodes-stats.html
INFO:build_docs:   - en/elasticsearch/reference/5.x/cluster-pending.html
INFO:build_docs:   - en/elasticsearch/reference/5.x/cluster-remote-info.html
INFO:build_docs:   - en/elasticsearch/reference/5.x/cluster-reroute.html
INFO:build_docs:   - en/elasticsearch/reference/5.x/cluster-state.html
INFO:build_docs:   - en/elasticsearch/reference/5.x/cluster-stats.html
INFO:build_docs:   - en/elasticsearch/reference/5.x/cluster-update-settings.html
INFO:build_docs:   - en/elasticsearch/reference/5.x/docs-bulk.html
INFO:build_docs:   - en/elasticsearch/reference/5.x/docs-delete-by-query.html
INFO:build_docs:   - en/elasticsearch/reference/5.x/docs-delete.html
INFO:build_docs:   - en/elasticsearch/reference/5.x/docs-get.html
INFO:build_docs:   - en/elasticsearch/reference/5.x/docs-index_.html
INFO:build_docs:   - en/elasticsearch/reference/5.x/docs-multi-get.html
INFO:build_docs:   - en/elasticsearch/reference/5.x/docs-multi-termvectors.html
INFO:build_docs:   - en/elasticsearch/reference/5.x/docs-reindex.html
INFO:build_docs:   - en/elasticsearch/reference/5.x/docs-termvectors.html
INFO:build_docs:   - en/elasticsearch/reference/5.x/docs-update-by-query.html
INFO:build_docs:   - en/elasticsearch/reference/5.x/docs-update.html
INFO:build_docs:   - en/elasticsearch/reference/5.x/indices-aliases.html
INFO:build_docs:   - en/elasticsearch/reference/5.x/indices-analyze.html
INFO:build_docs:   - en/elasticsearch/reference/5.x/indices-clearcache.html
INFO:build_docs:   - en/elasticsearch/reference/5.x/indices-create-index.html
INFO:build_docs:   - en/elasticsearch/reference/5.x/indices-delete-index.html
INFO:build_docs:   - en/elasticsearch/reference/5.x/indices-exists.html
INFO:build_docs:   - en/elasticsearch/reference/5.x/indices-flush.html
INFO:build_docs:   - en/elasticsearch/reference/5.x/indices-forcemerge.html
INFO:build_docs:   - en/elasticsearch/reference/5.x/indices-get-field-mapping.html
INFO:build_docs:   - en/elasticsearch/reference/5.x/indices-get-index.html
INFO:build_docs:   - en/elasticsearch/reference/5.x/indices-get-mapping.html
INFO:build_docs:   - en/elasticsearch/reference/5.x/indices-get-settings.html
INFO:build_docs:   - en/elasticsearch/reference/5.x/indices-open-close.html
INFO:build_docs:   - en/elasticsearch/reference/5.x/indices-put-mapping.html
INFO:build_docs:   - en/elasticsearch/reference/5.x/indices-recovery.html
INFO:build_docs:   - en/elasticsearch/reference/5.x/indices-refresh.html
INFO:build_docs:   - en/elasticsearch/reference/5.x/indices-rollover-index.html
INFO:build_docs:   - en/elasticsearch/reference/5.x/indices-segments.html
INFO:build_docs:   - en/elasticsearch/reference/5.x/indices-shards-stores.html
INFO:build_docs:   - en/elasticsearch/reference/5.x/indices-shrink-index.html
INFO:build_docs:   - en/elasticsearch/reference/5.x/indices-stats.html
INFO:build_docs:   - en/elasticsearch/reference/5.x/indices-synced-flush.html
INFO:build_docs:   - en/elasticsearch/reference/5.x/indices-templates.html
INFO:build_docs:   - en/elasticsearch/reference/5.x/indices-types-exists.html
INFO:build_docs:   - en/elasticsearch/reference/5.x/indices-update-settings.html
INFO:build_docs:   - en/elasticsearch/reference/5.x/indices-upgrade.html
INFO:build_docs:   - en/elasticsearch/reference/5.x/modules-scripting.html
INFO:build_docs:   - en/elasticsearch/reference/5.x/modules-snapshots.html
INFO:build_docs:   - en/elasticsearch/reference/5.x/search-count.html
INFO:build_docs:   - en/elasticsearch/reference/5.x/search-explain.html
INFO:build_docs:   - en/elasticsearch/reference/5.x/search-field-caps.html
INFO:build_docs:   - en/elasticsearch/reference/5.x/search-field-stats.html
INFO:build_docs:   - en/elasticsearch/reference/5.x/search-multi-search.html
INFO:build_docs:   - en/elasticsearch/reference/5.x/search-percolate.html
INFO:build_docs:   - en/elasticsearch/reference/5.x/search-request-scroll.html
INFO:build_docs:   - en/elasticsearch/reference/5.x/search-search.html
INFO:build_docs:   - en/elasticsearch/reference/5.x/search-shards.html
INFO:build_docs:   - en/elasticsearch/reference/5.x/search-suggesters.html
INFO:build_docs:   - en/elasticsearch/reference/5.x/search-template.html
INFO:build_docs:   - en/elasticsearch/reference/5.x/search-validate.html
INFO:build_docs:   - en/elasticsearch/reference/5.x/tasks.html
INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/elasticsearch/client/javascript-api/6.x/_api_reference.html:
INFO:build_docs:   - en/elasticsearch/reference/6.x/secure-settings.html
INFO:build_docs:   - en/elasticsearch/reference/current/frozen.html
INFO:build_docs:   - en/elasticsearch/reference/current/ml-file-structure.html
INFO:build_docs:   - en/elasticsearch/reference/current/security-api-get-user-privileges.html
INFO:build_docs:   - en/migration/current/migration-api-deprecation.html
INFO:build_docs:   - en/monitoring/current/appendix-api-bulk.html
INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/elasticsearch/client/javascript-api/7.x/_api_reference.html:
INFO:build_docs:   - en/elasticsearch/reference/current/frozen.html
INFO:build_docs:   - en/elasticsearch/reference/current/ml-file-structure.html
INFO:build_docs:   - en/elasticsearch/reference/current/security-api-get-user-privileges.html
INFO:build_docs:   - en/migration/current/migration-api-deprecation.html
INFO:build_docs:   - en/monitoring/current/appendix-api-bulk.html
INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/elasticsearch/client/javascript-api/current/_api_reference.html:
INFO:build_docs:   - en/elasticsearch/reference/current/frozen.html
INFO:build_docs:   - en/elasticsearch/reference/current/ml-file-structure.html
INFO:build_docs:   - en/elasticsearch/reference/current/security-api-get-user-privileges.html
INFO:build_docs:   - en/migration/current/migration-api-deprecation.html
INFO:build_docs:   - en/monitoring/current/appendix-api-bulk.html
INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/elasticsearch/client/javascript-api/master/_api_reference.html:
INFO:build_docs:   - en/elasticsearch/reference/current/delete-data-frame-transform.html
INFO:build_docs:   - en/elasticsearch/reference/current/frozen.html
INFO:build_docs:   - en/elasticsearch/reference/current/get-data-frame-transform-stats.html
INFO:build_docs:   - en/elasticsearch/reference/current/get-data-frame-transform.html
INFO:build_docs:   - en/elasticsearch/reference/current/ml-file-structure.html
INFO:build_docs:   - en/elasticsearch/reference/current/preview-data-frame-transform.html
INFO:build_docs:   - en/elasticsearch/reference/current/put-data-frame-transform.html
INFO:build_docs:   - en/elasticsearch/reference/current/security-api-get-user-privileges.html
INFO:build_docs:   - en/elasticsearch/reference/current/start-data-frame-transform.html
INFO:build_docs:   - en/elasticsearch/reference/current/stop-data-frame-transform.html
INFO:build_docs:   - en/migration/current/migration-api-deprecation.html
INFO:build_docs:   - en/monitoring/current/appendix-api-bulk.html
INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/shield/2.0/_using_elasticsearch_http_rest_clients_with_shield.html:
INFO:build_docs:   - en/elasticsearch/client/javascript-api/current/auth-reference.html
INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/shield/2.1/_using_elasticsearch_http_rest_clients_with_shield.html:
INFO:build_docs:   - en/elasticsearch/client/javascript-api/current/auth-reference.html
INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/shield/2.2/_using_elasticsearch_http_rest_clients_with_shield.html:
INFO:build_docs:   - en/elasticsearch/client/javascript-api/current/auth-reference.html
INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/shield/2.3/_using_elasticsearch_http_rest_clients_with_shield.html:
INFO:build_docs:   - en/elasticsearch/client/javascript-api/current/auth-reference.html
INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/shield/2.4/_using_elasticsearch_http_rest_clients_with_shield.html:
INFO:build_docs:   - en/elasticsearch/client/javascript-api/current/auth-reference.html
INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/shield/current/_using_elasticsearch_http_rest_clients_with_shield.html:
INFO:build_docs:   - en/elasticsearch/client/javascript-api/current/auth-reference.html
INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/shield/shield-1.0/_http_rest_clients.html:
INFO:build_docs:   - en/elasticsearch/client/javascript-api/current/auth-reference.html
INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/shield/shield-1.1/_http_rest_clients.html:
INFO:build_docs:   - en/elasticsearch/client/javascript-api/current/auth-reference.html
INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/shield/shield-1.2/_http_rest_clients.html:
INFO:build_docs:   - en/elasticsearch/client/javascript-api/current/auth-reference.html
INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/shield/shield-1.3/_using_elasticsearch_http_rest_clients_with_shield.html:
INFO:build_docs:   - en/elasticsearch/client/javascript-api/current/auth-reference.html
INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/x-pack/5.0/http-clients.html:
INFO:build_docs:   - en/elasticsearch/client/javascript-api/current/auth-reference.html
INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/x-pack/5.1/http-clients.html:
INFO:build_docs:   - en/elasticsearch/client/javascript-api/current/auth-reference.html
INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/x-pack/5.2/http-clients.html:
INFO:build_docs:   - en/elasticsearch/client/javascript-api/current/auth-reference.html
INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/x-pack/5.3/http-clients.html:
INFO:build_docs:   - en/elasticsearch/client/javascript-api/current/auth-reference.html
INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/x-pack/5.4/http-clients.html:
INFO:build_docs:   - en/elasticsearch/client/javascript-api/current/auth-reference.html
INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/x-pack/5.5/http-clients.html:
INFO:build_docs:   - en/elasticsearch/client/javascript-api/current/auth-reference.html
INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/x-pack/5.6/http-clients.html:
INFO:build_docs:   - en/elasticsearch/client/javascript-api/current/auth-reference.html
INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/x-pack/6.0/http-clients.html:
INFO:build_docs:   - en/elasticsearch/client/javascript-api/current/auth-reference.html
INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/x-pack/6.1/http-clients.html:
INFO:build_docs:   - en/elasticsearch/client/javascript-api/current/auth-reference.html
INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/x-pack/6.2/http-clients.html:
INFO:build_docs:   - en/elasticsearch/client/javascript-api/current/auth-reference.html
INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/x-pack/current/http-clients.html:
INFO:build_docs:   - en/elasticsearch/client/javascript-api/current/auth-reference.html
```

The upshot is that we link to `auth-reference.html` all over the place. Because we do that you should probably make that page. If you already have that then maybe just rename it? Or maybe just make a little page that points at where you do document it. We currently don't take redirects into account for these things, sadly.

You also reference some broken links from your docs. I'm no sure what it is up there but those are usually fairly easy to fix.

**Comment by nik9000** [comment]
I opened https://github.com/elastic/elasticsearch-js/pull/799 for what I hope are the last of the broken links.

**Comment by nik9000** [comment]
I need one more PR in the elasticsearch-js client before we can merge this: https://github.com/elastic/elasticsearch-js/pull/801

**Comment by nik9000** [comment]
That PR is in! We're ready to merge this any time you are ready @delvedor!

**Pull request merged**
