### PR TITLE
ECS 1.1.0 docs for release

### PR DESCRIPTION
**Pull request by webmat**
Long time fan, first pull request to docs :-)

I'm in the process of releasing ECS 1.1.0, which has a live `1.1` branch, for docs adjustments.

### CODE REVIEW

**Comment by nik9000** [comment]
@elasticmachine, run elasticsearch-ci/docs

**Comment by webmat** [comment]
I've looked at the docs for 1.1 and current, and both look good to me.

However at the bottom of the diffs I can see changes to the logstash docs.

@nik9000 are these just recent merges that are about to be deployed to the main site? Kind of like a race condition I shouldn't worry about?

If the logstash docs diff isn't a worry, I'm good to merge this. But since I'm not familiar with the repo & stuff, I'd love to get confirmation that this is fine :-)

**Comment by nik9000** [comment]
Indeed, sometimes things will sneak in to the diff, especially in the docs
repo. This is the price we pay to test new books and new branches and new
sources. This doesn't happen in the prs to the other repos because they
don't have to test new sources and stuff.

**Comment by webmat** [comment]
Great, thank you @karenzone and @nik9000

**Pull request merged**
