### PR TITLE
Bumps version to 8.8

### PR DESCRIPTION
**Pull request by nastasha-solomon**
Bumps the Docs version to 8.8.

### CODE REVIEW

**Comment by nastasha-solomon** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by nastasha-solomon** [comment]
Rerunning to try and resolve these issues:

````
00:54:44 INFO:build_docs:Bad cross-document links:
00:54:45 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/agent/nodejs/3.x/log-correlation.html contains broken links to:
00:54:45 INFO:build_docs:   - en/apm/guide/8.8/log-correlation.html#_ingest_your_logs_into_elasticsearch
00:54:45 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/agent/nodejs/current/log-correlation.html contains broken links to:
00:54:45 INFO:build_docs:   - en/apm/guide/8.8/log-correlation.html#_ingest_your_logs_into_elasticsearch
00:54:45 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/agent/nodejs/master/log-correlation.html contains broken links to:
00:54:45 INFO:build_docs:   - en/apm/guide/8.8/log-correlation.html#_ingest_your_logs_into_elasticsearch
````

**Comment by nastasha-solomon** [comment]
Re-running checks didn't fix the broken cross-links.

**Comment by nastasha-solomon** [comment]
Waiting for https://github.com/elastic/apm-agent-nodejs/pull/3371 to be merged. Will need to re-run the CI checks for this PR after.

**Comment by nastasha-solomon** [comment]
@elasticmachine run elasticsearch-ci/docs

**Review by KOTungseth — APPROVED** [review]

**Pull request merged**
