### PR TITLE
Update branches for 2.13.0 release

### PR DESCRIPTION
**Pull request by obierlaire**
Related to https://github.com/elastic/dev/issues/1814

Updates the branches for: ECE, ecctl for the
upcoming ECE 2.13.0 release.

### CODE REVIEW

**Review by gtback — APPROVED** [review]
LGTM!

The build error relates to a missing file:

> 09:31:39 INFO:build_docs:asciidoctor: ERROR: index.asciidoc: line 8: include file not found: /tmp/docsbuild/Q0aeS3yX89/cloud/docs/ece-version.asciidoc

Am I right thinking that this file gets generated dynamically as part of the ECE release? We'll have to find some way to make it available for docs builds.

**Comment by kellyemurphy** [comment]
> Am I right thinking that this file gets generated dynamically as part of the ECE release?

IIRC, that's the case. The Cloud writers have been creating an empty file, that isn't saved, so that we can get the builds to pass.

**Review by kellyemurphy — APPROVED** [review]

**Comment by kellyemurphy** [comment]
@obierlaire confirmed that this error is expected and we can just merge/get someone to help us merge when it's time.

**Comment by gtback** [comment]
> @obierlaire confirmed that this error is expected and we can just merge/get someone to help us merge when it's time.

@obierlaire @kellyemurphy are you saying that the file will be committed to the cloud repo as part of the release? We don't run any of the cloud build steps as part of the docs build, so unless the file already exists when the doc build starts, it will fail after this is merged.

**Comment by nrichers** [comment]
> @obierlaire @kellyemurphy are you saying that the file will be committed to the cloud repo as part of the release? We don't run any of the cloud build steps as part of the docs build, so unless the file already exists when the doc build starts, it will fail after this is merged.

@gtback I believe https://github.com/elastic/cloud/commit/83abcae3075089c532988ff17acf3e067e109856 from @alpar-t introduced a change to the ECE docs that uses a generated ece-version.asciidoc file. This change breaks our `docbldece` doc build alias without the workaround described by @kellyemurphy and by the looks of it can also break the CI checks in the elastic/docs repo.

Alpár, you had added this ece-version.asciidoc file to the .gitignore, but is there a way we can modify your implementation to avoid these build breaks?

**Comment by alpar-t** [comment]
@nrichers The purpose of the change was to make it so we keep a single record of truth about the version across the repo. We do have a pattern where we do commit other generated files into the repo and check that they match what we expect, but I'm not sure it's warranted in this case. Could we just run the one Gradle target `./gradlew generateVersionFile` as part of the affected builds to generate the version file ?

**Comment by nrichers** [comment]
@alpar-t let's move the discussion for how to best address this into https://github.com/elastic/cloud/issues/92457? 

For now, I will force merge this PR as we need to get the 2.13 release out.

**Comment by gtback** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by nrichers** [comment]
@elasticmachine  run elasticsearch-ci/docs

**Comment by nrichers** [comment]
Good news, bad news scenario: on the upside, the ECE 2.13 docs build now passes, thanks to https://github.com/elastic/cloud/pull/95054. On the downside, we now have a bunch of broken links:

```
15:21:30 INFO:build_docs:Bad cross-document links:
15:21:30 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/cloud-enterprise/2.13/ece-cloud-ingest-data.html contains broken links to:
15:21:30 INFO:build_docs:   - en/fleet/7.16/elastic-agent-installation-configuration.html
15:21:30 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/cloud-enterprise/2.13/ece-enable-ccs.html contains broken links to:
15:21:30 INFO:build_docs:   - en/elasticsearch/reference/7.16/modules-remote-clusters.html#gateway-nodes-selection
15:21:30 INFO:build_docs:   - en/elasticsearch/reference/7.16/modules-remote-clusters.html#proxy-mode
15:21:30 INFO:build_docs:   - en/elasticsearch/reference/7.16/modules-remote-clusters.html#sniff-mode
15:21:30 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/cloud-enterprise/current/ece-cloud-ingest-data.html contains broken links to:
15:21:30 INFO:build_docs:   - en/fleet/7.16/elastic-agent-installation-configuration.html
15:21:30 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/cloud-enterprise/current/ece-enable-ccs.html contains broken links to:
15:21:30 INFO:build_docs:   - en/elasticsearch/reference/7.16/modules-remote-clusters.html#gateway-nodes-selection
15:21:30 INFO:build_docs:   - en/elasticsearch/reference/7.16/modules-remote-clusters.html#proxy-mode
15:21:30 INFO:build_docs:   - en/elasticsearch/reference/7.16/modules-remote-clusters.html#sniff-mode
15:21:30 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/enterprise-search/7.10/license-management.html contains broken links to:
15:21:30 INFO:build_docs:   - en/cloud-enterprise/current/ece-add-license.html#ece_add_a_license
15:21:30 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/enterprise-search/7.11/license-management.html contains broken links to:
15:21:30 INFO:build_docs:   - en/cloud-enterprise/current/ece-add-license.html#ece_add_a_license
15:21:30 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/enterprise-search/7.12/license-management.html contains broken links to:
15:21:30 INFO:build_docs:   - en/cloud-enterprise/current/ece-add-license.html#ece_add_a_license
15:21:30 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/enterprise-search/7.13/license-management.html contains broken links to:
15:21:30 INFO:build_docs:   - en/cloud-enterprise/current/ece-add-license.html#ece_add_a_license
15:21:30 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/enterprise-search/7.14/license-management.html contains broken links to:
15:21:30 INFO:build_docs:   - en/cloud-enterprise/current/ece-add-license.html#ece_add_a_license
15:21:30 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/enterprise-search/7.15/license-management.html contains broken links to:
15:21:30 INFO:build_docs:   - en/cloud-enterprise/current/ece-add-license.html#ece_add_a_license
15:21:30 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/enterprise-search/7.16/license-management.html contains broken links to:
15:21:30 INFO:build_docs:   - en/cloud-enterprise/current/ece-add-license.html#ece_add_a_license
15:21:30 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/enterprise-search/7.17/license-management.html contains broken links to:
15:21:30 INFO:build_docs:   - en/cloud-enterprise/current/ece-add-license.html#ece_add_a_license
15:21:30 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/enterprise-search/7.9/license-management.html contains broken links to:
15:21:30 INFO:build_docs:   - en/cloud-enterprise/current/ece-add-license.html#ece_add_a_license
15:21:30 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/enterprise-search/8.0/license-management.html contains broken links to:
15:21:30 INFO:build_docs:   - en/cloud-enterprise/current/ece-add-license.html#ece_add_a_license
15:21:30 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/enterprise-search/current/license-management.html contains broken links to:
15:21:30 INFO:build_docs:   - en/cloud-enterprise/current/ece-add-license.html#ece_add_a_license
15:21:30 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/enterprise-search/master/license-management.html contains broken links to:
15:21:30 INFO:build_docs:   - en/cloud-enterprise/current/ece-add-license.html#ece_add_a_license
```

I will work on fixing these.

**Comment by nrichers** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by nrichers** [comment]
Looks to be live now, so I'm going to sign off for the evening:

image

**Pull request merged**
