### PR TITLE
update APM section title

### PR DESCRIPTION
**Pull request by jalvz**

### CODE REVIEW

**Comment by dedemorton** [comment]
@jalvz I'm concerned about renaming this document to "APM overview" because users might not realize that the document includes getting started content. We already have this problem with the Stack Overview. It was renamed hastily when X-Pack went away, but the name doesn't convey the depth and variety of content that the Stack Overview contains. We are meeting sometime soon (probably this week) to discuss renaming the book, so I would suggest waiting for a resolution on that question before renaming the APM book. 

Unless you plan to remove the installation content and have just the overview info.

**Comment by jalvz** [comment]
Thanks @dedemorton 
This change was suggested by @makwarth , i think waiting for the meeting is a good idea

**Comment by makwarth** [comment]
Waiting for the resolution sounds good. 

FYI, I suggested this change as we're introducing Release notes for APM, which don't feel right to place under "Getting started", so I went with "Overview", as it was used in other documents already.

**Comment by dedemorton** [comment]
Go ahead and change the title  to use caps (as suggested above), and I'll merge this.

**Comment by jalvz** [comment]
And im back, sorry for the long way @dedemorton, updated now!

**Comment by makwarth** [comment]
thanks @jalvz

**Pull request merged**
