### PR TITLE
Use EUI compatible admonitions

### PR DESCRIPTION
**Pull request by nik9000**
Replaces the admonition images that we're using with images that are
more compatible with EUI.

### CODE REVIEW

**Comment by nik9000** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by nik9000** [comment]
@elasticmachine run elasticsearch-ci/docs rebuild

**Comment by nik9000** [comment]
@Adrian-J, here are some examples:
* http://docs_1342.docs-preview.app.elstc.co/guide/en/elasticsearch/reference/7.5/backup-cluster-configuration.html#backup-cluster-configuration
* http://docs_1342.docs-preview.app.elstc.co/guide/en/elasticsearch/reference/7.5/removal-of-types.html
* http://docs_1342.docs-preview.app.elstc.co/guide/en/elasticsearch/reference/7.5/dense-vector.html
* http://docs_1342.docs-preview.app.elstc.co/guide/en/elasticsearch/reference/7.5/docker.html#_notes_for_production_use_and_defaults
* http://docs_1342.docs-preview.app.elstc.co/guide/en/elasticsearch/reference/7.5/setup-xpack-client.html

**Comment by Adrian-J** [comment]
@nik9000 Something is off with the scale of these icons. I think they need to sit in containers, I see that the div.icon container is set to 80x80px. I can export these icons in a container of this size, but you'd have to disable resizing. Is that doable? 

New icons in containers live [here](https://elasticsearch.box.com/s/7onlda485caijl2q33v3r8mmyt5mzxl5)

**Comment by nik9000** [comment]
They do look a little weird, don't they. I can size them however we need I think. Let's talk over a higher bandwidth channel in a few hours so I can understand you a little quicker.

**Comment by nik9000** [comment]
@elasticmachine run elasticsearch-ci/docs rebuild

**Comment by nik9000** [comment]
@Adrian-J, I've pushed an update. When the elasticsearch-ci/docs build finishes the preview should update. The text is a consistent font-size and the icon is the same size.

**Comment by Adrian-J** [comment]
Looks good @nik9000 ! Thanks for tweaking it

**Comment by nik9000** [comment]
Thanks for reviewing @JoshMock and @Adrian-J!

**Pull request merged**
