### PR TITLE
Add main branch to elasticsearch-net repo to docs build

### PR DESCRIPTION
**Pull request by szabosteve**
## Overview

This PR adds a main branch to the `elasticsearch-net` repo in the conf.yml file of the docs build system.

### Note

**It cannot be merged until _after_ a "main" branch is created in the elasticsearch-net repo.**

### CODE REVIEW

**Review by lcawl — APPROVED** [review]
LGTM!

**Review by gtback — APPROVED** [review]
LGTM!

**Review by stevejgordon — APPROVED** [review]
LGTM!

**Comment by szabosteve** [comment]
@elasticmachine test this please

**Comment by szabosteve** [comment]
The master branch of the Beats repo has been renamed in the meantime. So I merge this PR as otherwise, https://github.com/elastic/docs/pull/2337 will also fail.

**Pull request merged**
