### PR TITLE
[Docs release] Bump current version to 8.3

### PR DESCRIPTION
**Pull request by joepeeples**
Changes the "current" version of Elastic documentation to 8.3.

### CODE REVIEW

**Comment by joepeeples** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by joepeeples** [comment]
@elasticmachine run elasticsearch-ci/docs rebuild

**Review by gtback — APPROVED** [review]

**Comment by kilfoyle** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by joepeeples** [comment]
@elasticmachine run elasticsearch-ci/docs rebuild

**Comment by kilfoyle** [comment]
I've opened https://github.com/elastic/elasticsearch-js/pull/1721 to try and resolve the following errors.

```
15:38:25 INFO:build_docs:Bad cross-document links:
15:38:25 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/elasticsearch/client/javascript-api/8.2/api-reference.html contains broken links to:
15:38:25 INFO:build_docs:   - en/elasticsearch/reference/current/security-api-activate-user-profile.html
15:38:25 INFO:build_docs:   - en/elasticsearch/reference/current/security-api-get-user-profile.html
15:38:25 INFO:build_docs:   - en/elasticsearch/reference/current/security-api-update-user-profile-data.html
15:38:25 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/elasticsearch/client/javascript-api/8.3/api-reference.html contains broken links to:
15:38:25 INFO:build_docs:   - en/elasticsearch/reference/current/security-api-activate-user-profile.html
15:38:25 INFO:build_docs:   - en/elasticsearch/reference/current/security-api-get-user-profile.html
15:38:25 INFO:build_docs:   - en/elasticsearch/reference/current/security-api-update-user-profile-data.html
15:38:25 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/elasticsearch/client/javascript-api/current/api-reference.html contains broken links to:
15:38:25 INFO:build_docs:   - en/elasticsearch/reference/current/security-api-activate-user-profile.html
15:38:25 INFO:build_docs:   - en/elasticsearch/reference/current/security-api-get-user-profile.html
15:38:25 INFO:build_docs:   - en/elasticsearch/reference/current/security-api-update-user-profile-data.html
15:38:25 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/elasticsearch/client/javascript-api/master/api-reference.html contains broken links to:
15:38:25 INFO:build_docs:   - en/elasticsearch/reference/current/security-api-activate-user-profile.html
15:38:25 INFO:build_docs:   - en/elasticsearch/reference/current/security-api-get-user-profile.html
15:38:25 INFO:build_docs:   - en/elasticsearch/reference/current/security-api-update-user-profile-data.html
```

**Comment by kilfoyle** [comment]
@elasticmachine run elasticsearch-ci/docs rebuild

**Comment by kilfoyle** [comment]
@elasticmachine run elasticsearch-ci/docs rebuild

**Comment by kilfoyle** [comment]
All clean now! 🎉

**Pull request merged**
